// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type ClinicWaitTimeAggregate struct {
	ID                 int32
	KbmCode            string
	DoctorID           string
	DepartmentCode     string
	Gender             string
	AgeBracket         string
	AverageWaitMinutes int32
	SampleCount        int32
	UpdatedAt          sql.NullTime
}

type Icd10Catalog struct {
	Icd10Code   string
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedDt   sql.NullTime
	DeletedBy   uuid.NullUUID
}

type Icd10PolyclinicMapping struct {
	Icd10Code      string
	PolyclinicCode string
	CreatedAt      sql.NullTime
	DeletedDt      sql.NullTime
	DeletedBy      uuid.NullUUID
}

type KbmCatalog struct {
	KbmCode     string
	KbmName     string
	Description sql.NullString
	BodySystem  sql.NullString
	IsActive    bool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedDt   sql.NullTime
	DeletedBy   uuid.NullUUID
}

type KbmIcd10Mapping struct {
	KbmCode   string
	Icd10Code string
	IsPrimary sql.NullBool
	CreatedAt sql.NullTime
	DeletedDt sql.NullTime
	DeletedBy uuid.NullUUID
}

type KbmPolyclinicMapping struct {
	KbmCode        string
	PolyclinicCode string
	CreatedAt      sql.NullTime
	DeletedDt      sql.NullTime
	DeletedBy      uuid.NullUUID
}

type MasterTindakan struct {
	KodeTindakan string
	NamaTindakan string
	BasePrice    string
	IsActive     bool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedDt    sql.NullTime
	DeletedBy    uuid.NullUUID
}

type MedicalAction struct {
	ID              string
	MedicalRecordID string
	ActionCode      string
	ActionName      string
	Price           string
	Notes           sql.NullString
	CreatedAt       sql.NullTime
	DeletedDt       sql.NullTime
	DeletedBy       uuid.NullUUID
}

type MedicalRecord struct {
	ID                     string
	EncounterNo            string
	Mrn                    string
	Icd10Codes             []string
	Notes                  sql.NullString
	CreatedAt              sql.NullTime
	UpdatedAt              sql.NullTime
	BloodPressureSystolic  sql.NullInt32
	BloodPressureDiastolic sql.NullInt32
	Temperature            sql.NullString
	HeartRate              sql.NullInt32
	Status                 sql.NullString
	StartedAt              sql.NullTime
	CompletedAt            sql.NullTime
	DoctorID               sql.NullString
	DepartmentCode         sql.NullString
	Diagnosis              sql.NullString
	Gender                 sql.NullString
	AgeBracket             sql.NullString
	KbmCode                sql.NullString
	KbmName                sql.NullString
	Icd10MappingStatus     sql.NullString
	DeletedDt              sql.NullTime
	DeletedBy              uuid.NullUUID
}

type OutboxEvent struct {
	ID            string
	AggregateType string
	EventType     string
	Payload       json.RawMessage
	Status        string
	CreatedAt     sql.NullTime
}

type Polyclinic struct {
	Code        string
	Name        string
	Description sql.NullString
	IsActive    bool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedDt   sql.NullTime
	DeletedBy   uuid.NullUUID
}

type TindakanPolyclinicMapping struct {
	KodeTindakan   string
	PolyclinicCode string
	CreatedAt      sql.NullTime
	DeletedDt      sql.NullTime
	DeletedBy      uuid.NullUUID
}
