// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Invoice struct {
	ID          string
	EncounterNo string
	RelatedID   string
	Amount      string
	Status      string
	CreatedAt   sql.NullTime
}
