// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Invoice struct {
	ID          string
	EncounterNo string
	TotalAmount string
	Status      string
	CreatedAt   sql.NullTime
	PaidAt      sql.NullTime
	DeletedDt   sql.NullTime
	DeletedBy   uuid.NullUUID
}

type InvoiceItem struct {
	ID          string
	InvoiceID   string
	ItemType    string
	Description string
	Amount      string
	CreatedAt   sql.NullTime
	DeletedDt   sql.NullTime
	DeletedBy   uuid.NullUUID
}

type OutboxEvent struct {
	ID            string
	AggregateType string
	EventType     string
	Payload       json.RawMessage
	Status        string
	CreatedAt     sql.NullTime
}
