// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (id, encounter_no, total_amount, status)
VALUES ($1, $2, $3, $4)
RETURNING id, encounter_no, total_amount, status, created_at, paid_at, deleted_dt, deleted_by
`

type CreateInvoiceParams struct {
	ID          string
	EncounterNo string
	TotalAmount string
	Status      string
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, createInvoice,
		arg.ID,
		arg.EncounterNo,
		arg.TotalAmount,
		arg.Status,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.EncounterNo,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.DeletedDt,
		&i.DeletedBy,
	)
	return i, err
}

const createInvoiceItem = `-- name: CreateInvoiceItem :one
INSERT INTO invoice_items (id, invoice_id, item_type, description, amount)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, invoice_id, item_type, description, amount, created_at, deleted_dt, deleted_by
`

type CreateInvoiceItemParams struct {
	ID          string
	InvoiceID   string
	ItemType    string
	Description string
	Amount      string
}

func (q *Queries) CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) (InvoiceItem, error) {
	row := q.db.QueryRowContext(ctx, createInvoiceItem,
		arg.ID,
		arg.InvoiceID,
		arg.ItemType,
		arg.Description,
		arg.Amount,
	)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ItemType,
		&i.Description,
		&i.Amount,
		&i.CreatedAt,
		&i.DeletedDt,
		&i.DeletedBy,
	)
	return i, err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (id, aggregate_type, event_type, payload, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, aggregate_type, event_type, payload, status, created_at
`

type CreateOutboxEventParams struct {
	ID            string
	AggregateType string
	EventType     string
	Payload       json.RawMessage
	Status        string
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRowContext(ctx, createOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.EventType,
		arg.Payload,
		arg.Status,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveUnpaidInvoiceByEncounterNo = `-- name: GetActiveUnpaidInvoiceByEncounterNo :one
SELECT id, encounter_no, total_amount, status, created_at, paid_at, deleted_dt, deleted_by
FROM invoices
WHERE encounter_no = $1 AND status = 'UNPAID' AND deleted_dt IS NULL
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetActiveUnpaidInvoiceByEncounterNo(ctx context.Context, encounterNo string) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getActiveUnpaidInvoiceByEncounterNo, encounterNo)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.EncounterNo,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.DeletedDt,
		&i.DeletedBy,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, encounter_no, total_amount, status, created_at, paid_at, deleted_dt, deleted_by
FROM invoices
WHERE id = $1 AND deleted_dt IS NULL LIMIT 1
`

func (q *Queries) GetInvoice(ctx context.Context, id string) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.EncounterNo,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.DeletedDt,
		&i.DeletedBy,
	)
	return i, err
}

const getInvoiceByEncounterNo = `-- name: GetInvoiceByEncounterNo :one
SELECT id, encounter_no, total_amount, status, created_at, paid_at, deleted_dt, deleted_by
FROM invoices
WHERE encounter_no = $1 AND deleted_dt IS NULL 
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetInvoiceByEncounterNo(ctx context.Context, encounterNo string) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceByEncounterNo, encounterNo)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.EncounterNo,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.DeletedDt,
		&i.DeletedBy,
	)
	return i, err
}

const getInvoiceItemByPattern = `-- name: GetInvoiceItemByPattern :one
SELECT it.id, it.invoice_id, it.item_type, it.description, it.amount, it.created_at, it.deleted_dt, it.deleted_by, i.status as invoice_status
FROM invoice_items it
JOIN invoices i ON i.id = it.invoice_id
WHERE i.encounter_no = $1 AND it.description LIKE $2 AND it.deleted_dt IS NULL AND i.deleted_dt IS NULL
LIMIT 1
`

type GetInvoiceItemByPatternParams struct {
	EncounterNo string
	Description string
}

type GetInvoiceItemByPatternRow struct {
	ID            string
	InvoiceID     string
	ItemType      string
	Description   string
	Amount        string
	CreatedAt     sql.NullTime
	DeletedDt     sql.NullTime
	DeletedBy     uuid.NullUUID
	InvoiceStatus string
}

func (q *Queries) GetInvoiceItemByPattern(ctx context.Context, arg GetInvoiceItemByPatternParams) (GetInvoiceItemByPatternRow, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceItemByPattern, arg.EncounterNo, arg.Description)
	var i GetInvoiceItemByPatternRow
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ItemType,
		&i.Description,
		&i.Amount,
		&i.CreatedAt,
		&i.DeletedDt,
		&i.DeletedBy,
		&i.InvoiceStatus,
	)
	return i, err
}

const getInvoiceItems = `-- name: GetInvoiceItems :many
SELECT id, invoice_id, item_type, description, amount, created_at, deleted_dt, deleted_by
FROM invoice_items
WHERE invoice_id = $1 AND deleted_dt IS NULL
ORDER BY created_at ASC
`

func (q *Queries) GetInvoiceItems(ctx context.Context, invoiceID string) ([]InvoiceItem, error) {
	rows, err := q.db.QueryContext(ctx, getInvoiceItems, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceItem
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.ItemType,
			&i.Description,
			&i.Amount,
			&i.CreatedAt,
			&i.DeletedDt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvoicesByEncounterNo = `-- name: GetInvoicesByEncounterNo :many
SELECT id, encounter_no, total_amount, status, created_at, paid_at, deleted_dt, deleted_by
FROM invoices
WHERE encounter_no = $1 AND deleted_dt IS NULL
ORDER BY created_at ASC
`

func (q *Queries) GetInvoicesByEncounterNo(ctx context.Context, encounterNo string) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, getInvoicesByEncounterNo, encounterNo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.EncounterNo,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
			&i.PaidAt,
			&i.DeletedDt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, aggregate_type, event_type, payload, status, created_at
FROM outbox_events
WHERE status = 'PENDING'
ORDER BY created_at ASC LIMIT 100
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context) ([]OutboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, getPendingOutboxEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recalculateInvoiceTotal = `-- name: RecalculateInvoiceTotal :one
UPDATE invoices
SET total_amount = (
    SELECT COALESCE(SUM(amount), 0)
    FROM invoice_items
    WHERE invoice_id = $1 AND deleted_dt IS NULL
)
WHERE id = $1 AND deleted_dt IS NULL
RETURNING id, encounter_no, total_amount, status, created_at, paid_at, deleted_dt, deleted_by
`

func (q *Queries) RecalculateInvoiceTotal(ctx context.Context, invoiceID string) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, recalculateInvoiceTotal, invoiceID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.EncounterNo,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.DeletedDt,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteInvoiceItemByPattern = `-- name: SoftDeleteInvoiceItemByPattern :exec
UPDATE invoice_items
SET deleted_dt = CURRENT_TIMESTAMP
WHERE invoice_id = $1 AND description LIKE $2 AND deleted_dt IS NULL
`

type SoftDeleteInvoiceItemByPatternParams struct {
	InvoiceID   string
	Description string
}

func (q *Queries) SoftDeleteInvoiceItemByPattern(ctx context.Context, arg SoftDeleteInvoiceItemByPatternParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteInvoiceItemByPattern, arg.InvoiceID, arg.Description)
	return err
}

const updateInvoiceAmount = `-- name: UpdateInvoiceAmount :one
UPDATE invoices
SET total_amount = total_amount + $2
WHERE id = $1 AND deleted_dt IS NULL
RETURNING id, encounter_no, total_amount, status, created_at, paid_at, deleted_dt, deleted_by
`

type UpdateInvoiceAmountParams struct {
	ID          string
	TotalAmount string
}

func (q *Queries) UpdateInvoiceAmount(ctx context.Context, arg UpdateInvoiceAmountParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, updateInvoiceAmount, arg.ID, arg.TotalAmount)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.EncounterNo,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.DeletedDt,
		&i.DeletedBy,
	)
	return i, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices
SET status = $2, paid_at = $3
WHERE id = $1 AND deleted_dt IS NULL
RETURNING id, encounter_no, total_amount, status, created_at, paid_at, deleted_dt, deleted_by
`

type UpdateInvoiceStatusParams struct {
	ID     string
	Status string
	PaidAt sql.NullTime
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, updateInvoiceStatus, arg.ID, arg.Status, arg.PaidAt)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.EncounterNo,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.DeletedDt,
		&i.DeletedBy,
	)
	return i, err
}

const updateOutboxEventStatus = `-- name: UpdateOutboxEventStatus :exec
UPDATE outbox_events
SET status = $2
WHERE id = $1
`

type UpdateOutboxEventStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateOutboxEventStatus(ctx context.Context, arg UpdateOutboxEventStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOutboxEventStatus, arg.ID, arg.Status)
	return err
}
