// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: proto/billing/v1/billing.proto

package billingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvoiceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemType      string                 `protobuf:"bytes,1,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"` // "ACTION" or "MEDICINE"
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceItem) Reset() {
	*x = InvoiceItem{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceItem) ProtoMessage() {}

func (x *InvoiceItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceItem.ProtoReflect.Descriptor instead.
func (*InvoiceItem) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *InvoiceItem) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *InvoiceItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InvoiceItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GenerateInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncounterNo   string                 `protobuf:"bytes,1,opt,name=encounter_no,json=encounterNo,proto3" json:"encounter_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateInvoiceRequest) Reset() {
	*x = GenerateInvoiceRequest{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInvoiceRequest) ProtoMessage() {}

func (x *GenerateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GenerateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateInvoiceRequest) GetEncounterNo() string {
	if x != nil {
		return x.EncounterNo
	}
	return ""
}

type GenerateInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	InvoiceId     string                 `protobuf:"bytes,2,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	Items         []*InvoiceItem         `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateInvoiceResponse) Reset() {
	*x = GenerateInvoiceResponse{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInvoiceResponse) ProtoMessage() {}

func (x *GenerateInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInvoiceResponse.ProtoReflect.Descriptor instead.
func (*GenerateInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateInvoiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateInvoiceResponse) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *GenerateInvoiceResponse) GetItems() []*InvoiceItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GenerateInvoiceResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GenerateInvoiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PayInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	AmountPaid    float64                `protobuf:"fixed64,2,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayInvoiceRequest) Reset() {
	*x = PayInvoiceRequest{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayInvoiceRequest) ProtoMessage() {}

func (x *PayInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayInvoiceRequest.ProtoReflect.Descriptor instead.
func (*PayInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *PayInvoiceRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *PayInvoiceRequest) GetAmountPaid() float64 {
	if x != nil {
		return x.AmountPaid
	}
	return 0
}

type PayInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayInvoiceResponse) Reset() {
	*x = PayInvoiceResponse{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayInvoiceResponse) ProtoMessage() {}

func (x *PayInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayInvoiceResponse.ProtoReflect.Descriptor instead.
func (*PayInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *PayInvoiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PayInvoiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_billing_v1_billing_proto protoreflect.FileDescriptor

const file_proto_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/billing/v1/billing.proto\x12\n" +
	"billing.v1\"d\n" +
	"\vInvoiceItem\x12\x1b\n" +
	"\titem_type\x18\x01 \x01(\tR\bitemType\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\";\n" +
	"\x16GenerateInvoiceRequest\x12!\n" +
	"\fencounter_no\x18\x01 \x01(\tR\vencounterNo\"\xbe\x01\n" +
	"\x17GenerateInvoiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x02 \x01(\tR\tinvoiceId\x12-\n" +
	"\x05items\x18\x03 \x03(\v2\x17.billing.v1.InvoiceItemR\x05items\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"S\n" +
	"\x11PayInvoiceRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x1f\n" +
	"\vamount_paid\x18\x02 \x01(\x01R\n" +
	"amountPaid\"H\n" +
	"\x12PayInvoiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb9\x01\n" +
	"\x0eBillingService\x12Z\n" +
	"\x0fGenerateInvoice\x12\".billing.v1.GenerateInvoiceRequest\x1a#.billing.v1.GenerateInvoiceResponse\x12K\n" +
	"\n" +
	"PayInvoice\x12\x1d.billing.v1.PayInvoiceRequest\x1a\x1e.billing.v1.PayInvoiceResponseBHZFgithub.com/aliube/go-micro-simrs-one/shared/proto/billing/v1;billingv1b\x06proto3"

var (
	file_proto_billing_v1_billing_proto_rawDescOnce sync.Once
	file_proto_billing_v1_billing_proto_rawDescData []byte
)

func file_proto_billing_v1_billing_proto_rawDescGZIP() []byte {
	file_proto_billing_v1_billing_proto_rawDescOnce.Do(func() {
		file_proto_billing_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_billing_v1_billing_proto_rawDesc), len(file_proto_billing_v1_billing_proto_rawDesc)))
	})
	return file_proto_billing_v1_billing_proto_rawDescData
}

var file_proto_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_billing_v1_billing_proto_goTypes = []any{
	(*InvoiceItem)(nil),             // 0: billing.v1.InvoiceItem
	(*GenerateInvoiceRequest)(nil),  // 1: billing.v1.GenerateInvoiceRequest
	(*GenerateInvoiceResponse)(nil), // 2: billing.v1.GenerateInvoiceResponse
	(*PayInvoiceRequest)(nil),       // 3: billing.v1.PayInvoiceRequest
	(*PayInvoiceResponse)(nil),      // 4: billing.v1.PayInvoiceResponse
}
var file_proto_billing_v1_billing_proto_depIdxs = []int32{
	0, // 0: billing.v1.GenerateInvoiceResponse.items:type_name -> billing.v1.InvoiceItem
	1, // 1: billing.v1.BillingService.GenerateInvoice:input_type -> billing.v1.GenerateInvoiceRequest
	3, // 2: billing.v1.BillingService.PayInvoice:input_type -> billing.v1.PayInvoiceRequest
	2, // 3: billing.v1.BillingService.GenerateInvoice:output_type -> billing.v1.GenerateInvoiceResponse
	4, // 4: billing.v1.BillingService.PayInvoice:output_type -> billing.v1.PayInvoiceResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_billing_v1_billing_proto_init() }
func file_proto_billing_v1_billing_proto_init() {
	if File_proto_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_billing_v1_billing_proto_rawDesc), len(file_proto_billing_v1_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_proto_billing_v1_billing_proto_depIdxs,
		MessageInfos:      file_proto_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_proto_billing_v1_billing_proto = out.File
	file_proto_billing_v1_billing_proto_goTypes = nil
	file_proto_billing_v1_billing_proto_depIdxs = nil
}
