// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Patient struct {
	Mrn       string
	Name      string
	Nik       string
	Dob       string
	CreatedAt sql.NullTime
	UserID    uuid.NullUUID
}
