CREATE TABLE master_tindakan (
    kode_tindakan VARCHAR(50) PRIMARY KEY,
    nama_tindakan VARCHAR(255) NOT NULL,
    base_price NUMERIC(15,2) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
