ALTER TABLE medical_records ADD COLUMN deleted_dt TIMESTAMP WITH TIME ZONE;
ALTER TABLE medical_records ADD COLUMN deleted_by UUID;
ALTER TABLE medical_actions ADD COLUMN deleted_dt TIMESTAMP WITH TIME ZONE;
ALTER TABLE medical_actions ADD COLUMN deleted_by UUID;
ALTER TABLE kbm_catalog ADD COLUMN deleted_dt TIMESTAMP WITH TIME ZONE;
ALTER TABLE kbm_catalog ADD COLUMN deleted_by UUID;
ALTER TABLE icd10_catalog ADD COLUMN deleted_dt TIMESTAMP WITH TIME ZONE;
ALTER TABLE icd10_catalog ADD COLUMN deleted_by UUID;
ALTER TABLE master_tindakan ADD COLUMN deleted_dt TIMESTAMP WITH TIME ZONE;
ALTER TABLE master_tindakan ADD COLUMN deleted_by UUID;
ALTER TABLE polyclinics ADD COLUMN deleted_dt TIMESTAMP WITH TIME ZONE;
ALTER TABLE polyclinics ADD COLUMN deleted_by UUID;
ALTER TABLE kbm_icd10_mappings ADD COLUMN deleted_dt TIMESTAMP WITH TIME ZONE;
ALTER TABLE kbm_icd10_mappings ADD COLUMN deleted_by UUID;
ALTER TABLE kbm_polyclinic_mappings ADD COLUMN deleted_dt TIMESTAMP WITH TIME ZONE;
ALTER TABLE kbm_polyclinic_mappings ADD COLUMN deleted_by UUID;
ALTER TABLE icd10_polyclinic_mappings ADD COLUMN deleted_dt TIMESTAMP WITH TIME ZONE;
ALTER TABLE icd10_polyclinic_mappings ADD COLUMN deleted_by UUID;
ALTER TABLE tindakan_polyclinic_mappings ADD COLUMN deleted_dt TIMESTAMP WITH TIME ZONE;
ALTER TABLE tindakan_polyclinic_mappings ADD COLUMN deleted_by UUID;
