syntax = "proto3";

package billing.v1;

option go_package = "github.com/aliube/go-micro-simrs-one/shared/proto/billing/v1;billingv1";

service BillingService {
  // Charge patient for an item. 
  rpc CreateInvoice (CreateInvoiceRequest) returns (CreateInvoiceResponse);
}

message CreateInvoiceRequest {
  string encounter_no = 1;
  string related_id = 2; // e.g. prescription_id
  double amount = 3;
}

message CreateInvoiceResponse {
  bool success = 1;
  string invoice_id = 2;
  string message = 3;
}
