// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: shared/proto/billing/v1/billing.proto

package billingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncounterNo   string                 `protobuf:"bytes,1,opt,name=encounter_no,json=encounterNo,proto3" json:"encounter_no,omitempty"`
	RelatedId     string                 `protobuf:"bytes,2,opt,name=related_id,json=relatedId,proto3" json:"related_id,omitempty"` // e.g. prescription_id
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceRequest) Reset() {
	*x = CreateInvoiceRequest{}
	mi := &file_shared_proto_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceRequest) ProtoMessage() {}

func (x *CreateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*CreateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInvoiceRequest) GetEncounterNo() string {
	if x != nil {
		return x.EncounterNo
	}
	return ""
}

func (x *CreateInvoiceRequest) GetRelatedId() string {
	if x != nil {
		return x.RelatedId
	}
	return ""
}

func (x *CreateInvoiceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	InvoiceId     string                 `protobuf:"bytes,2,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceResponse) Reset() {
	*x = CreateInvoiceResponse{}
	mi := &file_shared_proto_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceResponse) ProtoMessage() {}

func (x *CreateInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceResponse.ProtoReflect.Descriptor instead.
func (*CreateInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInvoiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateInvoiceResponse) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *CreateInvoiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_shared_proto_billing_v1_billing_proto protoreflect.FileDescriptor

const file_shared_proto_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"%shared/proto/billing/v1/billing.proto\x12\n" +
	"billing.v1\"p\n" +
	"\x14CreateInvoiceRequest\x12!\n" +
	"\fencounter_no\x18\x01 \x01(\tR\vencounterNo\x12\x1d\n" +
	"\n" +
	"related_id\x18\x02 \x01(\tR\trelatedId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"j\n" +
	"\x15CreateInvoiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x02 \x01(\tR\tinvoiceId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2f\n" +
	"\x0eBillingService\x12T\n" +
	"\rCreateInvoice\x12 .billing.v1.CreateInvoiceRequest\x1a!.billing.v1.CreateInvoiceResponseBHZFgithub.com/aliube/go-micro-simrs-one/shared/proto/billing/v1;billingv1b\x06proto3"

var (
	file_shared_proto_billing_v1_billing_proto_rawDescOnce sync.Once
	file_shared_proto_billing_v1_billing_proto_rawDescData []byte
)

func file_shared_proto_billing_v1_billing_proto_rawDescGZIP() []byte {
	file_shared_proto_billing_v1_billing_proto_rawDescOnce.Do(func() {
		file_shared_proto_billing_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_billing_v1_billing_proto_rawDesc), len(file_shared_proto_billing_v1_billing_proto_rawDesc)))
	})
	return file_shared_proto_billing_v1_billing_proto_rawDescData
}

var file_shared_proto_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_proto_billing_v1_billing_proto_goTypes = []any{
	(*CreateInvoiceRequest)(nil),  // 0: billing.v1.CreateInvoiceRequest
	(*CreateInvoiceResponse)(nil), // 1: billing.v1.CreateInvoiceResponse
}
var file_shared_proto_billing_v1_billing_proto_depIdxs = []int32{
	0, // 0: billing.v1.BillingService.CreateInvoice:input_type -> billing.v1.CreateInvoiceRequest
	1, // 1: billing.v1.BillingService.CreateInvoice:output_type -> billing.v1.CreateInvoiceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_billing_v1_billing_proto_init() }
func file_shared_proto_billing_v1_billing_proto_init() {
	if File_shared_proto_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_billing_v1_billing_proto_rawDesc), len(file_shared_proto_billing_v1_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_shared_proto_billing_v1_billing_proto_depIdxs,
		MessageInfos:      file_shared_proto_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_shared_proto_billing_v1_billing_proto = out.File
	file_shared_proto_billing_v1_billing_proto_goTypes = nil
	file_shared_proto_billing_v1_billing_proto_depIdxs = nil
}
