syntax = "proto3";

package pharmacy.v1;

option go_package = "github.com/aliube/go-micro-simrs-one/shared/proto/pharmacy/v1;pharmacyv1";

service PharmacyService {
  // Initiates prescription. Reserves stock (Lock).
  rpc CreatePrescription (CreatePrescriptionRequest) returns (CreatePrescriptionResponse);
  
  // Dispenses the prescription (after payment)
  rpc DispensePrescription (DispensePrescriptionRequest) returns (DispensePrescriptionResponse);

  // Saga Compensation: Release reserved stock
  rpc RollbackPrescription (RollbackPrescriptionRequest) returns (RollbackPrescriptionResponse);

  // Queue Estimation
  rpc GetEstimatedWaitTime (GetEstimatedWaitTimeRequest) returns (GetEstimatedWaitTimeResponse);

  // Master Data
  rpc GetMasterObat (GetMasterObatRequest) returns (GetMasterObatResponse);
  rpc GetMasterObatByPoli (GetMasterObatByPoliRequest) returns (GetMasterObatByPoliResponse);
}

message GetEstimatedWaitTimeRequest {
  bool is_compounded = 1;
  string diagnosis = 2;
  string doctor_id = 3;
  string department_code = 4;
  string gender = 5;
  string age_bracket = 6;
}

message GetEstimatedWaitTimeResponse {
  int64 estimated_minutes = 1;
}

message PrescriptionItem {
  string item_code = 1;
  string item_name = 2;
  int32 quantity = 3;
  string dosage = 4;
}

message CreatePrescriptionRequest {
  string encounter_no = 1;
  bool is_compounded = 2;
  repeated PrescriptionItem items = 3;
  string notes = 4;
  string diagnosis = 5;
  string gender = 6;
  string age_bracket = 7;
  string doctor_id = 8;
  string department_code = 9;
}

message CreatePrescriptionResponse {
  bool success = 1;
  string prescription_id = 2;
  double amount_to_bill = 3;
  string message = 4;
}

message DispensePrescriptionRequest {
  string prescription_id = 1;
}

message DispensePrescriptionResponse {
  bool success = 1;
  string message = 2;
}

message RollbackPrescriptionRequest {
  string prescription_id = 1;
}

message RollbackPrescriptionResponse {
  bool success = 1;
  string message = 2;
}

// Master Data
message GetMasterObatRequest {
  int32 page = 1;
  int32 page_size = 2;
  string search_name = 3;
  string search_code = 4;
}

message MasterObat {
  string item_code = 1;
  string name = 2;
  double price = 3;
}

message GetMasterObatResponse {
  repeated MasterObat data = 1;
  int32 total_count = 2;
}

message GetMasterObatByPoliRequest {
  int32 page = 1;
  int32 page_size = 2;
  string poli_code = 3;
  string search_name = 4;
  string search_code = 5;
}

message GetMasterObatByPoliResponse {
  repeated MasterObat data = 1;
  int32 total_count = 2;
}
