// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.26.1
// source: pharmacy.proto

package pharmacyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PharmacyService_CreatePrescription_FullMethodName   = "/pharmacy.v1.PharmacyService/CreatePrescription"
	PharmacyService_DispensePrescription_FullMethodName = "/pharmacy.v1.PharmacyService/DispensePrescription"
	PharmacyService_RollbackPrescription_FullMethodName = "/pharmacy.v1.PharmacyService/RollbackPrescription"
	PharmacyService_GetEstimatedWaitTime_FullMethodName = "/pharmacy.v1.PharmacyService/GetEstimatedWaitTime"
	PharmacyService_GetMasterObat_FullMethodName        = "/pharmacy.v1.PharmacyService/GetMasterObat"
	PharmacyService_GetMasterObatByPoli_FullMethodName  = "/pharmacy.v1.PharmacyService/GetMasterObatByPoli"
)

// PharmacyServiceClient is the client API for PharmacyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PharmacyServiceClient interface {
	// Initiates prescription. Reserves stock (Lock).
	CreatePrescription(ctx context.Context, in *CreatePrescriptionRequest, opts ...grpc.CallOption) (*CreatePrescriptionResponse, error)
	// Dispenses the prescription (after payment)
	DispensePrescription(ctx context.Context, in *DispensePrescriptionRequest, opts ...grpc.CallOption) (*DispensePrescriptionResponse, error)
	// Saga Compensation: Release reserved stock
	RollbackPrescription(ctx context.Context, in *RollbackPrescriptionRequest, opts ...grpc.CallOption) (*RollbackPrescriptionResponse, error)
	// Queue Estimation
	GetEstimatedWaitTime(ctx context.Context, in *GetEstimatedWaitTimeRequest, opts ...grpc.CallOption) (*GetEstimatedWaitTimeResponse, error)
	// Master Data
	GetMasterObat(ctx context.Context, in *GetMasterObatRequest, opts ...grpc.CallOption) (*GetMasterObatResponse, error)
	GetMasterObatByPoli(ctx context.Context, in *GetMasterObatByPoliRequest, opts ...grpc.CallOption) (*GetMasterObatByPoliResponse, error)
}

type pharmacyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPharmacyServiceClient(cc grpc.ClientConnInterface) PharmacyServiceClient {
	return &pharmacyServiceClient{cc}
}

func (c *pharmacyServiceClient) CreatePrescription(ctx context.Context, in *CreatePrescriptionRequest, opts ...grpc.CallOption) (*CreatePrescriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePrescriptionResponse)
	err := c.cc.Invoke(ctx, PharmacyService_CreatePrescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) DispensePrescription(ctx context.Context, in *DispensePrescriptionRequest, opts ...grpc.CallOption) (*DispensePrescriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispensePrescriptionResponse)
	err := c.cc.Invoke(ctx, PharmacyService_DispensePrescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) RollbackPrescription(ctx context.Context, in *RollbackPrescriptionRequest, opts ...grpc.CallOption) (*RollbackPrescriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackPrescriptionResponse)
	err := c.cc.Invoke(ctx, PharmacyService_RollbackPrescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) GetEstimatedWaitTime(ctx context.Context, in *GetEstimatedWaitTimeRequest, opts ...grpc.CallOption) (*GetEstimatedWaitTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEstimatedWaitTimeResponse)
	err := c.cc.Invoke(ctx, PharmacyService_GetEstimatedWaitTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) GetMasterObat(ctx context.Context, in *GetMasterObatRequest, opts ...grpc.CallOption) (*GetMasterObatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMasterObatResponse)
	err := c.cc.Invoke(ctx, PharmacyService_GetMasterObat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) GetMasterObatByPoli(ctx context.Context, in *GetMasterObatByPoliRequest, opts ...grpc.CallOption) (*GetMasterObatByPoliResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMasterObatByPoliResponse)
	err := c.cc.Invoke(ctx, PharmacyService_GetMasterObatByPoli_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PharmacyServiceServer is the server API for PharmacyService service.
// All implementations must embed UnimplementedPharmacyServiceServer
// for forward compatibility.
type PharmacyServiceServer interface {
	// Initiates prescription. Reserves stock (Lock).
	CreatePrescription(context.Context, *CreatePrescriptionRequest) (*CreatePrescriptionResponse, error)
	// Dispenses the prescription (after payment)
	DispensePrescription(context.Context, *DispensePrescriptionRequest) (*DispensePrescriptionResponse, error)
	// Saga Compensation: Release reserved stock
	RollbackPrescription(context.Context, *RollbackPrescriptionRequest) (*RollbackPrescriptionResponse, error)
	// Queue Estimation
	GetEstimatedWaitTime(context.Context, *GetEstimatedWaitTimeRequest) (*GetEstimatedWaitTimeResponse, error)
	// Master Data
	GetMasterObat(context.Context, *GetMasterObatRequest) (*GetMasterObatResponse, error)
	GetMasterObatByPoli(context.Context, *GetMasterObatByPoliRequest) (*GetMasterObatByPoliResponse, error)
	mustEmbedUnimplementedPharmacyServiceServer()
}

// UnimplementedPharmacyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPharmacyServiceServer struct{}

func (UnimplementedPharmacyServiceServer) CreatePrescription(context.Context, *CreatePrescriptionRequest) (*CreatePrescriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePrescription not implemented")
}
func (UnimplementedPharmacyServiceServer) DispensePrescription(context.Context, *DispensePrescriptionRequest) (*DispensePrescriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispensePrescription not implemented")
}
func (UnimplementedPharmacyServiceServer) RollbackPrescription(context.Context, *RollbackPrescriptionRequest) (*RollbackPrescriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackPrescription not implemented")
}
func (UnimplementedPharmacyServiceServer) GetEstimatedWaitTime(context.Context, *GetEstimatedWaitTimeRequest) (*GetEstimatedWaitTimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEstimatedWaitTime not implemented")
}
func (UnimplementedPharmacyServiceServer) GetMasterObat(context.Context, *GetMasterObatRequest) (*GetMasterObatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMasterObat not implemented")
}
func (UnimplementedPharmacyServiceServer) GetMasterObatByPoli(context.Context, *GetMasterObatByPoliRequest) (*GetMasterObatByPoliResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMasterObatByPoli not implemented")
}
func (UnimplementedPharmacyServiceServer) mustEmbedUnimplementedPharmacyServiceServer() {}
func (UnimplementedPharmacyServiceServer) testEmbeddedByValue()                         {}

// UnsafePharmacyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PharmacyServiceServer will
// result in compilation errors.
type UnsafePharmacyServiceServer interface {
	mustEmbedUnimplementedPharmacyServiceServer()
}

func RegisterPharmacyServiceServer(s grpc.ServiceRegistrar, srv PharmacyServiceServer) {
	// If the following call panics, it indicates UnimplementedPharmacyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PharmacyService_ServiceDesc, srv)
}

func _PharmacyService_CreatePrescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePrescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).CreatePrescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_CreatePrescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).CreatePrescription(ctx, req.(*CreatePrescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_DispensePrescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispensePrescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).DispensePrescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_DispensePrescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).DispensePrescription(ctx, req.(*DispensePrescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_RollbackPrescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackPrescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).RollbackPrescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_RollbackPrescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).RollbackPrescription(ctx, req.(*RollbackPrescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_GetEstimatedWaitTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEstimatedWaitTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).GetEstimatedWaitTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_GetEstimatedWaitTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).GetEstimatedWaitTime(ctx, req.(*GetEstimatedWaitTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_GetMasterObat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMasterObatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).GetMasterObat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_GetMasterObat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).GetMasterObat(ctx, req.(*GetMasterObatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_GetMasterObatByPoli_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMasterObatByPoliRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).GetMasterObatByPoli(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_GetMasterObatByPoli_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).GetMasterObatByPoli(ctx, req.(*GetMasterObatByPoliRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PharmacyService_ServiceDesc is the grpc.ServiceDesc for PharmacyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PharmacyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pharmacy.v1.PharmacyService",
	HandlerType: (*PharmacyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePrescription",
			Handler:    _PharmacyService_CreatePrescription_Handler,
		},
		{
			MethodName: "DispensePrescription",
			Handler:    _PharmacyService_DispensePrescription_Handler,
		},
		{
			MethodName: "RollbackPrescription",
			Handler:    _PharmacyService_RollbackPrescription_Handler,
		},
		{
			MethodName: "GetEstimatedWaitTime",
			Handler:    _PharmacyService_GetEstimatedWaitTime_Handler,
		},
		{
			MethodName: "GetMasterObat",
			Handler:    _PharmacyService_GetMasterObat_Handler,
		},
		{
			MethodName: "GetMasterObatByPoli",
			Handler:    _PharmacyService_GetMasterObatByPoli_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pharmacy.proto",
}
