// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: pharmacy.proto

package pharmacyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEstimatedWaitTimeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsCompounded   bool                   `protobuf:"varint,1,opt,name=is_compounded,json=isCompounded,proto3" json:"is_compounded,omitempty"`
	Diagnosis      string                 `protobuf:"bytes,2,opt,name=diagnosis,proto3" json:"diagnosis,omitempty"`
	DoctorId       string                 `protobuf:"bytes,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DepartmentCode string                 `protobuf:"bytes,4,opt,name=department_code,json=departmentCode,proto3" json:"department_code,omitempty"`
	Gender         string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	AgeBracket     string                 `protobuf:"bytes,6,opt,name=age_bracket,json=ageBracket,proto3" json:"age_bracket,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetEstimatedWaitTimeRequest) Reset() {
	*x = GetEstimatedWaitTimeRequest{}
	mi := &file_pharmacy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEstimatedWaitTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEstimatedWaitTimeRequest) ProtoMessage() {}

func (x *GetEstimatedWaitTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEstimatedWaitTimeRequest.ProtoReflect.Descriptor instead.
func (*GetEstimatedWaitTimeRequest) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{0}
}

func (x *GetEstimatedWaitTimeRequest) GetIsCompounded() bool {
	if x != nil {
		return x.IsCompounded
	}
	return false
}

func (x *GetEstimatedWaitTimeRequest) GetDiagnosis() string {
	if x != nil {
		return x.Diagnosis
	}
	return ""
}

func (x *GetEstimatedWaitTimeRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *GetEstimatedWaitTimeRequest) GetDepartmentCode() string {
	if x != nil {
		return x.DepartmentCode
	}
	return ""
}

func (x *GetEstimatedWaitTimeRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *GetEstimatedWaitTimeRequest) GetAgeBracket() string {
	if x != nil {
		return x.AgeBracket
	}
	return ""
}

type GetEstimatedWaitTimeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EstimatedMinutes int64                  `protobuf:"varint,1,opt,name=estimated_minutes,json=estimatedMinutes,proto3" json:"estimated_minutes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetEstimatedWaitTimeResponse) Reset() {
	*x = GetEstimatedWaitTimeResponse{}
	mi := &file_pharmacy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEstimatedWaitTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEstimatedWaitTimeResponse) ProtoMessage() {}

func (x *GetEstimatedWaitTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEstimatedWaitTimeResponse.ProtoReflect.Descriptor instead.
func (*GetEstimatedWaitTimeResponse) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{1}
}

func (x *GetEstimatedWaitTimeResponse) GetEstimatedMinutes() int64 {
	if x != nil {
		return x.EstimatedMinutes
	}
	return 0
}

type PrescriptionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemCode      string                 `protobuf:"bytes,1,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Dosage        string                 `protobuf:"bytes,4,opt,name=dosage,proto3" json:"dosage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrescriptionItem) Reset() {
	*x = PrescriptionItem{}
	mi := &file_pharmacy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrescriptionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrescriptionItem) ProtoMessage() {}

func (x *PrescriptionItem) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrescriptionItem.ProtoReflect.Descriptor instead.
func (*PrescriptionItem) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{2}
}

func (x *PrescriptionItem) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *PrescriptionItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *PrescriptionItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PrescriptionItem) GetDosage() string {
	if x != nil {
		return x.Dosage
	}
	return ""
}

type CreatePrescriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EncounterNo    string                 `protobuf:"bytes,1,opt,name=encounter_no,json=encounterNo,proto3" json:"encounter_no,omitempty"`
	IsCompounded   bool                   `protobuf:"varint,2,opt,name=is_compounded,json=isCompounded,proto3" json:"is_compounded,omitempty"`
	Items          []*PrescriptionItem    `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Notes          string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	Diagnosis      string                 `protobuf:"bytes,5,opt,name=diagnosis,proto3" json:"diagnosis,omitempty"`
	Gender         string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	AgeBracket     string                 `protobuf:"bytes,7,opt,name=age_bracket,json=ageBracket,proto3" json:"age_bracket,omitempty"`
	DoctorId       string                 `protobuf:"bytes,8,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DepartmentCode string                 `protobuf:"bytes,9,opt,name=department_code,json=departmentCode,proto3" json:"department_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePrescriptionRequest) Reset() {
	*x = CreatePrescriptionRequest{}
	mi := &file_pharmacy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrescriptionRequest) ProtoMessage() {}

func (x *CreatePrescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrescriptionRequest.ProtoReflect.Descriptor instead.
func (*CreatePrescriptionRequest) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePrescriptionRequest) GetEncounterNo() string {
	if x != nil {
		return x.EncounterNo
	}
	return ""
}

func (x *CreatePrescriptionRequest) GetIsCompounded() bool {
	if x != nil {
		return x.IsCompounded
	}
	return false
}

func (x *CreatePrescriptionRequest) GetItems() []*PrescriptionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreatePrescriptionRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *CreatePrescriptionRequest) GetDiagnosis() string {
	if x != nil {
		return x.Diagnosis
	}
	return ""
}

func (x *CreatePrescriptionRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreatePrescriptionRequest) GetAgeBracket() string {
	if x != nil {
		return x.AgeBracket
	}
	return ""
}

func (x *CreatePrescriptionRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *CreatePrescriptionRequest) GetDepartmentCode() string {
	if x != nil {
		return x.DepartmentCode
	}
	return ""
}

type CreatePrescriptionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PrescriptionId string                 `protobuf:"bytes,2,opt,name=prescription_id,json=prescriptionId,proto3" json:"prescription_id,omitempty"`
	AmountToBill   float64                `protobuf:"fixed64,3,opt,name=amount_to_bill,json=amountToBill,proto3" json:"amount_to_bill,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePrescriptionResponse) Reset() {
	*x = CreatePrescriptionResponse{}
	mi := &file_pharmacy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrescriptionResponse) ProtoMessage() {}

func (x *CreatePrescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrescriptionResponse.ProtoReflect.Descriptor instead.
func (*CreatePrescriptionResponse) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePrescriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreatePrescriptionResponse) GetPrescriptionId() string {
	if x != nil {
		return x.PrescriptionId
	}
	return ""
}

func (x *CreatePrescriptionResponse) GetAmountToBill() float64 {
	if x != nil {
		return x.AmountToBill
	}
	return 0
}

func (x *CreatePrescriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DispensePrescriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrescriptionId string                 `protobuf:"bytes,1,opt,name=prescription_id,json=prescriptionId,proto3" json:"prescription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DispensePrescriptionRequest) Reset() {
	*x = DispensePrescriptionRequest{}
	mi := &file_pharmacy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispensePrescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispensePrescriptionRequest) ProtoMessage() {}

func (x *DispensePrescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispensePrescriptionRequest.ProtoReflect.Descriptor instead.
func (*DispensePrescriptionRequest) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{5}
}

func (x *DispensePrescriptionRequest) GetPrescriptionId() string {
	if x != nil {
		return x.PrescriptionId
	}
	return ""
}

type DispensePrescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispensePrescriptionResponse) Reset() {
	*x = DispensePrescriptionResponse{}
	mi := &file_pharmacy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispensePrescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispensePrescriptionResponse) ProtoMessage() {}

func (x *DispensePrescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispensePrescriptionResponse.ProtoReflect.Descriptor instead.
func (*DispensePrescriptionResponse) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{6}
}

func (x *DispensePrescriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DispensePrescriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RollbackPrescriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrescriptionId string                 `protobuf:"bytes,1,opt,name=prescription_id,json=prescriptionId,proto3" json:"prescription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RollbackPrescriptionRequest) Reset() {
	*x = RollbackPrescriptionRequest{}
	mi := &file_pharmacy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackPrescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackPrescriptionRequest) ProtoMessage() {}

func (x *RollbackPrescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackPrescriptionRequest.ProtoReflect.Descriptor instead.
func (*RollbackPrescriptionRequest) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{7}
}

func (x *RollbackPrescriptionRequest) GetPrescriptionId() string {
	if x != nil {
		return x.PrescriptionId
	}
	return ""
}

type RollbackPrescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackPrescriptionResponse) Reset() {
	*x = RollbackPrescriptionResponse{}
	mi := &file_pharmacy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackPrescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackPrescriptionResponse) ProtoMessage() {}

func (x *RollbackPrescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackPrescriptionResponse.ProtoReflect.Descriptor instead.
func (*RollbackPrescriptionResponse) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{8}
}

func (x *RollbackPrescriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackPrescriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Master Data
type GetMasterObatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchName    string                 `protobuf:"bytes,3,opt,name=search_name,json=searchName,proto3" json:"search_name,omitempty"`
	SearchCode    string                 `protobuf:"bytes,4,opt,name=search_code,json=searchCode,proto3" json:"search_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMasterObatRequest) Reset() {
	*x = GetMasterObatRequest{}
	mi := &file_pharmacy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMasterObatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMasterObatRequest) ProtoMessage() {}

func (x *GetMasterObatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMasterObatRequest.ProtoReflect.Descriptor instead.
func (*GetMasterObatRequest) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{9}
}

func (x *GetMasterObatRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMasterObatRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMasterObatRequest) GetSearchName() string {
	if x != nil {
		return x.SearchName
	}
	return ""
}

func (x *GetMasterObatRequest) GetSearchCode() string {
	if x != nil {
		return x.SearchCode
	}
	return ""
}

type MasterObat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemCode      string                 `protobuf:"bytes,1,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterObat) Reset() {
	*x = MasterObat{}
	mi := &file_pharmacy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterObat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterObat) ProtoMessage() {}

func (x *MasterObat) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterObat.ProtoReflect.Descriptor instead.
func (*MasterObat) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{10}
}

func (x *MasterObat) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *MasterObat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MasterObat) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetMasterObatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*MasterObat          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMasterObatResponse) Reset() {
	*x = GetMasterObatResponse{}
	mi := &file_pharmacy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMasterObatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMasterObatResponse) ProtoMessage() {}

func (x *GetMasterObatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMasterObatResponse.ProtoReflect.Descriptor instead.
func (*GetMasterObatResponse) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{11}
}

func (x *GetMasterObatResponse) GetData() []*MasterObat {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetMasterObatResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetMasterObatByPoliRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PoliCode      string                 `protobuf:"bytes,3,opt,name=poli_code,json=poliCode,proto3" json:"poli_code,omitempty"`
	SearchName    string                 `protobuf:"bytes,4,opt,name=search_name,json=searchName,proto3" json:"search_name,omitempty"`
	SearchCode    string                 `protobuf:"bytes,5,opt,name=search_code,json=searchCode,proto3" json:"search_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMasterObatByPoliRequest) Reset() {
	*x = GetMasterObatByPoliRequest{}
	mi := &file_pharmacy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMasterObatByPoliRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMasterObatByPoliRequest) ProtoMessage() {}

func (x *GetMasterObatByPoliRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMasterObatByPoliRequest.ProtoReflect.Descriptor instead.
func (*GetMasterObatByPoliRequest) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{12}
}

func (x *GetMasterObatByPoliRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMasterObatByPoliRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMasterObatByPoliRequest) GetPoliCode() string {
	if x != nil {
		return x.PoliCode
	}
	return ""
}

func (x *GetMasterObatByPoliRequest) GetSearchName() string {
	if x != nil {
		return x.SearchName
	}
	return ""
}

func (x *GetMasterObatByPoliRequest) GetSearchCode() string {
	if x != nil {
		return x.SearchCode
	}
	return ""
}

type GetMasterObatByPoliResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*MasterObat          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMasterObatByPoliResponse) Reset() {
	*x = GetMasterObatByPoliResponse{}
	mi := &file_pharmacy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMasterObatByPoliResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMasterObatByPoliResponse) ProtoMessage() {}

func (x *GetMasterObatByPoliResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMasterObatByPoliResponse.ProtoReflect.Descriptor instead.
func (*GetMasterObatByPoliResponse) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{13}
}

func (x *GetMasterObatByPoliResponse) GetData() []*MasterObat {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetMasterObatByPoliResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_pharmacy_proto protoreflect.FileDescriptor

const file_pharmacy_proto_rawDesc = "" +
	"\n" +
	"\x0epharmacy.proto\x12\vpharmacy.v1\"\xdf\x01\n" +
	"\x1bGetEstimatedWaitTimeRequest\x12#\n" +
	"\ris_compounded\x18\x01 \x01(\bR\fisCompounded\x12\x1c\n" +
	"\tdiagnosis\x18\x02 \x01(\tR\tdiagnosis\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\tR\bdoctorId\x12'\n" +
	"\x0fdepartment_code\x18\x04 \x01(\tR\x0edepartmentCode\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x1f\n" +
	"\vage_bracket\x18\x06 \x01(\tR\n" +
	"ageBracket\"K\n" +
	"\x1cGetEstimatedWaitTimeResponse\x12+\n" +
	"\x11estimated_minutes\x18\x01 \x01(\x03R\x10estimatedMinutes\"\x80\x01\n" +
	"\x10PrescriptionItem\x12\x1b\n" +
	"\titem_code\x18\x01 \x01(\tR\bitemCode\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x16\n" +
	"\x06dosage\x18\x04 \x01(\tR\x06dosage\"\xcb\x02\n" +
	"\x19CreatePrescriptionRequest\x12!\n" +
	"\fencounter_no\x18\x01 \x01(\tR\vencounterNo\x12#\n" +
	"\ris_compounded\x18\x02 \x01(\bR\fisCompounded\x123\n" +
	"\x05items\x18\x03 \x03(\v2\x1d.pharmacy.v1.PrescriptionItemR\x05items\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\x12\x1c\n" +
	"\tdiagnosis\x18\x05 \x01(\tR\tdiagnosis\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12\x1f\n" +
	"\vage_bracket\x18\a \x01(\tR\n" +
	"ageBracket\x12\x1b\n" +
	"\tdoctor_id\x18\b \x01(\tR\bdoctorId\x12'\n" +
	"\x0fdepartment_code\x18\t \x01(\tR\x0edepartmentCode\"\x9f\x01\n" +
	"\x1aCreatePrescriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fprescription_id\x18\x02 \x01(\tR\x0eprescriptionId\x12$\n" +
	"\x0eamount_to_bill\x18\x03 \x01(\x01R\famountToBill\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"F\n" +
	"\x1bDispensePrescriptionRequest\x12'\n" +
	"\x0fprescription_id\x18\x01 \x01(\tR\x0eprescriptionId\"R\n" +
	"\x1cDispensePrescriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x1bRollbackPrescriptionRequest\x12'\n" +
	"\x0fprescription_id\x18\x01 \x01(\tR\x0eprescriptionId\"R\n" +
	"\x1cRollbackPrescriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x89\x01\n" +
	"\x14GetMasterObatRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vsearch_name\x18\x03 \x01(\tR\n" +
	"searchName\x12\x1f\n" +
	"\vsearch_code\x18\x04 \x01(\tR\n" +
	"searchCode\"S\n" +
	"\n" +
	"MasterObat\x12\x1b\n" +
	"\titem_code\x18\x01 \x01(\tR\bitemCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"e\n" +
	"\x15GetMasterObatResponse\x12+\n" +
	"\x04data\x18\x01 \x03(\v2\x17.pharmacy.v1.MasterObatR\x04data\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xac\x01\n" +
	"\x1aGetMasterObatByPoliRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tpoli_code\x18\x03 \x01(\tR\bpoliCode\x12\x1f\n" +
	"\vsearch_name\x18\x04 \x01(\tR\n" +
	"searchName\x12\x1f\n" +
	"\vsearch_code\x18\x05 \x01(\tR\n" +
	"searchCode\"k\n" +
	"\x1bGetMasterObatByPoliResponse\x12+\n" +
	"\x04data\x18\x01 \x03(\v2\x17.pharmacy.v1.MasterObatR\x04data\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount2\x81\x05\n" +
	"\x0fPharmacyService\x12e\n" +
	"\x12CreatePrescription\x12&.pharmacy.v1.CreatePrescriptionRequest\x1a'.pharmacy.v1.CreatePrescriptionResponse\x12k\n" +
	"\x14DispensePrescription\x12(.pharmacy.v1.DispensePrescriptionRequest\x1a).pharmacy.v1.DispensePrescriptionResponse\x12k\n" +
	"\x14RollbackPrescription\x12(.pharmacy.v1.RollbackPrescriptionRequest\x1a).pharmacy.v1.RollbackPrescriptionResponse\x12k\n" +
	"\x14GetEstimatedWaitTime\x12(.pharmacy.v1.GetEstimatedWaitTimeRequest\x1a).pharmacy.v1.GetEstimatedWaitTimeResponse\x12V\n" +
	"\rGetMasterObat\x12!.pharmacy.v1.GetMasterObatRequest\x1a\".pharmacy.v1.GetMasterObatResponse\x12h\n" +
	"\x13GetMasterObatByPoli\x12'.pharmacy.v1.GetMasterObatByPoliRequest\x1a(.pharmacy.v1.GetMasterObatByPoliResponseBJZHgithub.com/aliube/go-micro-simrs-one/shared/proto/pharmacy/v1;pharmacyv1b\x06proto3"

var (
	file_pharmacy_proto_rawDescOnce sync.Once
	file_pharmacy_proto_rawDescData []byte
)

func file_pharmacy_proto_rawDescGZIP() []byte {
	file_pharmacy_proto_rawDescOnce.Do(func() {
		file_pharmacy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pharmacy_proto_rawDesc), len(file_pharmacy_proto_rawDesc)))
	})
	return file_pharmacy_proto_rawDescData
}

var file_pharmacy_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pharmacy_proto_goTypes = []any{
	(*GetEstimatedWaitTimeRequest)(nil),  // 0: pharmacy.v1.GetEstimatedWaitTimeRequest
	(*GetEstimatedWaitTimeResponse)(nil), // 1: pharmacy.v1.GetEstimatedWaitTimeResponse
	(*PrescriptionItem)(nil),             // 2: pharmacy.v1.PrescriptionItem
	(*CreatePrescriptionRequest)(nil),    // 3: pharmacy.v1.CreatePrescriptionRequest
	(*CreatePrescriptionResponse)(nil),   // 4: pharmacy.v1.CreatePrescriptionResponse
	(*DispensePrescriptionRequest)(nil),  // 5: pharmacy.v1.DispensePrescriptionRequest
	(*DispensePrescriptionResponse)(nil), // 6: pharmacy.v1.DispensePrescriptionResponse
	(*RollbackPrescriptionRequest)(nil),  // 7: pharmacy.v1.RollbackPrescriptionRequest
	(*RollbackPrescriptionResponse)(nil), // 8: pharmacy.v1.RollbackPrescriptionResponse
	(*GetMasterObatRequest)(nil),         // 9: pharmacy.v1.GetMasterObatRequest
	(*MasterObat)(nil),                   // 10: pharmacy.v1.MasterObat
	(*GetMasterObatResponse)(nil),        // 11: pharmacy.v1.GetMasterObatResponse
	(*GetMasterObatByPoliRequest)(nil),   // 12: pharmacy.v1.GetMasterObatByPoliRequest
	(*GetMasterObatByPoliResponse)(nil),  // 13: pharmacy.v1.GetMasterObatByPoliResponse
}
var file_pharmacy_proto_depIdxs = []int32{
	2,  // 0: pharmacy.v1.CreatePrescriptionRequest.items:type_name -> pharmacy.v1.PrescriptionItem
	10, // 1: pharmacy.v1.GetMasterObatResponse.data:type_name -> pharmacy.v1.MasterObat
	10, // 2: pharmacy.v1.GetMasterObatByPoliResponse.data:type_name -> pharmacy.v1.MasterObat
	3,  // 3: pharmacy.v1.PharmacyService.CreatePrescription:input_type -> pharmacy.v1.CreatePrescriptionRequest
	5,  // 4: pharmacy.v1.PharmacyService.DispensePrescription:input_type -> pharmacy.v1.DispensePrescriptionRequest
	7,  // 5: pharmacy.v1.PharmacyService.RollbackPrescription:input_type -> pharmacy.v1.RollbackPrescriptionRequest
	0,  // 6: pharmacy.v1.PharmacyService.GetEstimatedWaitTime:input_type -> pharmacy.v1.GetEstimatedWaitTimeRequest
	9,  // 7: pharmacy.v1.PharmacyService.GetMasterObat:input_type -> pharmacy.v1.GetMasterObatRequest
	12, // 8: pharmacy.v1.PharmacyService.GetMasterObatByPoli:input_type -> pharmacy.v1.GetMasterObatByPoliRequest
	4,  // 9: pharmacy.v1.PharmacyService.CreatePrescription:output_type -> pharmacy.v1.CreatePrescriptionResponse
	6,  // 10: pharmacy.v1.PharmacyService.DispensePrescription:output_type -> pharmacy.v1.DispensePrescriptionResponse
	8,  // 11: pharmacy.v1.PharmacyService.RollbackPrescription:output_type -> pharmacy.v1.RollbackPrescriptionResponse
	1,  // 12: pharmacy.v1.PharmacyService.GetEstimatedWaitTime:output_type -> pharmacy.v1.GetEstimatedWaitTimeResponse
	11, // 13: pharmacy.v1.PharmacyService.GetMasterObat:output_type -> pharmacy.v1.GetMasterObatResponse
	13, // 14: pharmacy.v1.PharmacyService.GetMasterObatByPoli:output_type -> pharmacy.v1.GetMasterObatByPoliResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pharmacy_proto_init() }
func file_pharmacy_proto_init() {
	if File_pharmacy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pharmacy_proto_rawDesc), len(file_pharmacy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pharmacy_proto_goTypes,
		DependencyIndexes: file_pharmacy_proto_depIdxs,
		MessageInfos:      file_pharmacy_proto_msgTypes,
	}.Build()
	File_pharmacy_proto = out.File
	file_pharmacy_proto_goTypes = nil
	file_pharmacy_proto_depIdxs = nil
}
