ALTER TABLE mapping_dokter_poli 
  ADD COLUMN IF NOT EXISTS days_of_week INTEGER[] NOT NULL DEFAULT '{1,2,3,4,5}',
  ADD COLUMN IF NOT EXISTS shift_start TIME NOT NULL DEFAULT '08:00:00',
  ADD COLUMN IF NOT EXISTS shift_end TIME NOT NULL DEFAULT '16:00:00';

ALTER TABLE mapping_perawat_poli 
  ADD COLUMN IF NOT EXISTS days_of_week INTEGER[] NOT NULL DEFAULT '{1,2,3,4,5}',
  ADD COLUMN IF NOT EXISTS shift_start TIME NOT NULL DEFAULT '08:00:00',
  ADD COLUMN IF NOT EXISTS shift_end TIME NOT NULL DEFAULT '16:00:00';
