-- 000003_add_auth_fields_and_staff_table.up.sql
ALTER TABLE users ADD COLUMN status VARCHAR(20) DEFAULT 'PENDING';
ALTER TABLE users ADD COLUMN force_change_password BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN last_login_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN deleted_dt TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN deleted_by UUID;
ALTER TABLE users ALTER COLUMN role DROP NOT NULL;

CREATE TABLE staff_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  nip VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(20),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  deleted_dt TIMESTAMP WITH TIME ZONE,
  deleted_by UUID
);
