// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: registration/v1/registration.proto

package registrationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterEncounterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Mrn            string                 `protobuf:"bytes,1,opt,name=mrn,proto3" json:"mrn,omitempty"`
	DepartmentCode string                 `protobuf:"bytes,2,opt,name=department_code,json=departmentCode,proto3" json:"department_code,omitempty"` // e.g. "IGD", "P01"
	DoctorId       string                 `protobuf:"bytes,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterEncounterRequest) Reset() {
	*x = RegisterEncounterRequest{}
	mi := &file_registration_v1_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEncounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEncounterRequest) ProtoMessage() {}

func (x *RegisterEncounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registration_v1_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEncounterRequest.ProtoReflect.Descriptor instead.
func (*RegisterEncounterRequest) Descriptor() ([]byte, []int) {
	return file_registration_v1_registration_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterEncounterRequest) GetMrn() string {
	if x != nil {
		return x.Mrn
	}
	return ""
}

func (x *RegisterEncounterRequest) GetDepartmentCode() string {
	if x != nil {
		return x.DepartmentCode
	}
	return ""
}

func (x *RegisterEncounterRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

type RegisterEncounterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EncounterNo   string                 `protobuf:"bytes,2,opt,name=encounter_no,json=encounterNo,proto3" json:"encounter_no,omitempty"` // Format: YYYYMM+dept_code+seq
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEncounterResponse) Reset() {
	*x = RegisterEncounterResponse{}
	mi := &file_registration_v1_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEncounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEncounterResponse) ProtoMessage() {}

func (x *RegisterEncounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registration_v1_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEncounterResponse.ProtoReflect.Descriptor instead.
func (*RegisterEncounterResponse) Descriptor() ([]byte, []int) {
	return file_registration_v1_registration_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterEncounterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterEncounterResponse) GetEncounterNo() string {
	if x != nil {
		return x.EncounterNo
	}
	return ""
}

func (x *RegisterEncounterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_registration_v1_registration_proto protoreflect.FileDescriptor

const file_registration_v1_registration_proto_rawDesc = "" +
	"\n" +
	"\"registration/v1/registration.proto\x12\x0fregistration.v1\"r\n" +
	"\x18RegisterEncounterRequest\x12\x10\n" +
	"\x03mrn\x18\x01 \x01(\tR\x03mrn\x12'\n" +
	"\x0fdepartment_code\x18\x02 \x01(\tR\x0edepartmentCode\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\tR\bdoctorId\"r\n" +
	"\x19RegisterEncounterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fencounter_no\x18\x02 \x01(\tR\vencounterNo\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x81\x01\n" +
	"\x13RegistrationService\x12j\n" +
	"\x11RegisterEncounter\x12).registration.v1.RegisterEncounterRequest\x1a*.registration.v1.RegisterEncounterResponseBRZPgithub.com/aliube/go-micro-simrs-one/shared/proto/registration/v1;registrationv1b\x06proto3"

var (
	file_registration_v1_registration_proto_rawDescOnce sync.Once
	file_registration_v1_registration_proto_rawDescData []byte
)

func file_registration_v1_registration_proto_rawDescGZIP() []byte {
	file_registration_v1_registration_proto_rawDescOnce.Do(func() {
		file_registration_v1_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registration_v1_registration_proto_rawDesc), len(file_registration_v1_registration_proto_rawDesc)))
	})
	return file_registration_v1_registration_proto_rawDescData
}

var file_registration_v1_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_registration_v1_registration_proto_goTypes = []any{
	(*RegisterEncounterRequest)(nil),  // 0: registration.v1.RegisterEncounterRequest
	(*RegisterEncounterResponse)(nil), // 1: registration.v1.RegisterEncounterResponse
}
var file_registration_v1_registration_proto_depIdxs = []int32{
	0, // 0: registration.v1.RegistrationService.RegisterEncounter:input_type -> registration.v1.RegisterEncounterRequest
	1, // 1: registration.v1.RegistrationService.RegisterEncounter:output_type -> registration.v1.RegisterEncounterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_registration_v1_registration_proto_init() }
func file_registration_v1_registration_proto_init() {
	if File_registration_v1_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registration_v1_registration_proto_rawDesc), len(file_registration_v1_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registration_v1_registration_proto_goTypes,
		DependencyIndexes: file_registration_v1_registration_proto_depIdxs,
		MessageInfos:      file_registration_v1_registration_proto_msgTypes,
	}.Build()
	File_registration_v1_registration_proto = out.File
	file_registration_v1_registration_proto_goTypes = nil
	file_registration_v1_registration_proto_depIdxs = nil
}
