CREATE TABLE IF NOT EXISTS medical_records (
    id VARCHAR(255) PRIMARY KEY,
    encounter_no VARCHAR(255) UNIQUE NOT NULL,
    mrn VARCHAR(255) NOT NULL,
    icd10_codes TEXT[],
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
