ALTER TABLE medical_records
ADD COLUMN IF NOT EXISTS respiratory_rate INT,
ADD COLUMN IF NOT EXISTS oxygen_saturation INT,
ADD COLUMN IF NOT EXISTS height NUMERIC(5,2),
ADD COLUMN IF NOT EXISTS weight NUMERIC(5,2),
ADD COLUMN IF NOT EXISTS bmi NUMERIC(4,1),
ADD COLUMN IF NOT EXISTS allergies TEXT;
