INSERT INTO icd10_catalog (icd10_code, name_en, name_id, chapter_code, block_code, is_active) VALUES
('A00.0', 'Cholera due to Vibrio cholerae 01, biovar cholerae', 'Kolera akibat Vibrio cholerae 01, biotipe cholerae', 'I', 'A00-A09', true),
('A01.0', 'Typhoid fever', 'Demam Tifoid', 'I', 'A00-A09', true),
('A09', 'Diarrhoea and gastroenteritis of presumed infectious origin', 'Diare dan gastroenteritis oleh penyebab infeksi tertentu', 'I', 'A00-A09', true),
('A15.0', 'Tuberculosis of lung, confirmed by sputum microscopy with or without culture', 'Tuberkulosis paru, terkonfirmasi secara mikroskopis dahak', 'I', 'A15-A19', true),
('B01.9', 'Varicella without complication', 'Cacar air tanpa komplikasi', 'I', 'B00-B09', true),
('B05.9', 'Measles without complication', 'Campak tanpa komplikasi', 'I', 'B00-B09', true),
('B20', 'Human immunodeficiency virus [HIV] disease resulting in infectious and parasitic diseases', 'Penyakit HIV yang menyebabkan penyakit infeksi dan parasit', 'I', 'B20-B24', true),
('C50.9', 'Malignant neoplasm: Breast, unspecified', 'Neoplasma ganas payudara, tidak ditentukan', 'II', 'C00-C97', true),
('C53.9', 'Malignant neoplasm: Cervix uteri, unspecified', 'Neoplasma ganas serviks uteri, tidak ditentukan', 'II', 'C00-C97', true),
('D50.9', 'Iron deficiency anaemia, unspecified', 'Anemia defisiensi besi, tidak ditentukan', 'III', 'D50-D53', true),
('D64.9', 'Anaemia, unspecified', 'Anemia, tidak ditentukan', 'III', 'D50-D89', true),
('E10.9', 'Type 1 diabetes mellitus without complications', 'Diabetes mellitus tipe 1 tanpa komplikasi', 'IV', 'E10-E14', true),
('E11.9', 'Type 2 diabetes mellitus without complications', 'Diabetes mellitus tipe 2 tanpa komplikasi', 'IV', 'E10-E14', true),
('E11.8', 'Type 2 diabetes mellitus with unspecified complications', 'Diabetes mellitus tipe 2 dengan komplikasi lain', 'IV', 'E10-E14', true),
('E78.5', 'Hyperlipidaemia, unspecified', 'Hiperlipidemia, tidak ditentukan', 'IV', 'E70-E90', true),
('F32.9', 'Depressive episode, unspecified', 'Episode depresi, tidak ditentukan', 'V', 'F30-F39', true),
('F41.9', 'Anxiety disorder, unspecified', 'Gangguan kecemasan, tidak ditentukan', 'V', 'F40-F48', true),
('G43.9', 'Migraine, unspecified', 'Migren, tidak ditentukan', 'VI', 'G40-G47', true),
('G47.0', 'Disorders of initiating and maintaining sleep [insomnias]', 'Gangguan memulai dan mempertahankan tidur [insomnia]', 'VI', 'G40-G47', true),
('H10.9', 'Conjunctivitis, unspecified', 'Konjungtivitis, tidak ditentukan', 'VII', 'H10-H13', true),
('H25.9', 'Senile cataract, unspecified', 'Katarak senilis, tidak ditentukan', 'VII', 'H25-H28', true),
('H65.9', 'Nonsuppurative otitis media, unspecified', 'Otitis media non-supuratif, tidak ditentukan', 'VIII', 'H65-H75', true),
('I10', 'Essential (primary) hypertension', 'Hipertensi esensial (primer)', 'IX', 'I10-I15', true),
('I11.0', 'Hypertensive heart disease with (congestive) heart failure', 'Penyakit jantung hipertensi dengan gagal jantung', 'IX', 'I10-I15', true),
('I50.0', 'Congestive heart failure', 'Gagal jantung kongestif', 'IX', 'I50-I52', true),
('I50.9', 'Heart failure, unspecified', 'Gagal jantung, tidak ditentukan', 'IX', 'I50-I52', true),
('I64', 'Stroke, not specified as haemorrhage or infarction', 'Stroke, tidak ditentukan sebagai pendarahan atau infark', 'IX', 'I60-I69', true),
('J00', 'Acute nasopharyngitis [common cold]', 'Nasofaringitis akut [common cold]', 'X', 'J00-J06', true),
('J06.9', 'Acute upper respiratory infection, unspecified', 'Infeksi saluran pernapasan atas akut, tidak ditentukan', 'X', 'J00-J06', true),
('J18.9', 'Pneumonia, unspecified', 'Pneumonia, tidak ditentukan', 'X', 'J09-J18', true),
('J45.9', 'Asthma, unspecified', 'Asma, tidak ditentukan', 'X', 'J40-J47', true),
('K21.9', 'Gastro-oesophageal reflux disease without oesophagitis', 'Penyakit refluks gastro-esofagus tanpa esofagitis (GERD)', 'XI', 'K20-K31', true),
('K27.9', 'Peptic ulcer, unspecified as acute or chronic, without haemorrhage or perforation', 'Tukak peptik, tidak ditentukan akut atau kronis', 'XI', 'K20-K31', true),
('K29.7', 'Gastritis, unspecified', 'Gastritis, tidak ditentukan', 'XI', 'K20-K31', true),
('K35.8', 'Other and unspecified acute appendicitis', 'Apendisitis akut lainnya dan tidak ditentukan', 'XI', 'K35-K38', true),
('L20.9', 'Atopic dermatitis, unspecified', 'Dermatitis atopik, tidak ditentukan', 'XII', 'L20-L30', true),
('L23.9', 'Allergic contact dermatitis, unspecified cause', 'Dermatitis kontak alergi, penyebab tidak ditentukan', 'XII', 'L20-L30', true),
('L50.9', 'Urticaria, unspecified', 'Urtikaria (biduran), tidak ditentukan', 'XII', 'L50-L54', true),
('M19.9', 'Osteoartritis, unspecified', 'Osteoartritis, tidak ditentukan', 'XIII', 'M15-M19', true),
('M54.5', 'Low back pain', 'Nyeri punggung bawah (LBP)', 'XIII', 'M50-M54', true),
('N18.9', 'Chronic kidney disease, unspecified', 'Penyakit ginjal kronis, tidak ditentukan', 'XIV', 'N17-N19', true),
('N39.0', 'Urinary tract infection, site not specified', 'Infeksi saluran kemih, lokasi tidak ditentukan', 'XIV', 'N30-N39', true),
('O20.0', 'Threatened abortion', 'Ancaman keguguran', 'XV', 'O20-O29', true),
('O80.9', 'Single spontaneous delivery, unspecified', 'Persalinan spontan tunggal, tidak ditentukan', 'XV', 'O80-O84', true),
('P07.3', 'Other preterm infants', 'Bayi prematur lainnya', 'XVI', 'P05-P08', true),
('Q05.9', 'Spina bifida, unspecified', 'Spina bifida, tidak ditentukan', 'XVII', 'Q00-Q07', true),
('R05', 'Cough', 'Batuk', 'XVIII', 'R00-R09', true),
('R07.4', 'Chest pain, unspecified', 'Nyeri dada, tidak ditentukan', 'XVIII', 'R00-R09', true),
('R50.9', 'Fever, unspecified', 'Demam, tidak ditentukan', 'XVIII', 'R50-R69', true),
('R51', 'Headache', 'Sakit kepala', 'XVIII', 'R50-R69', true),
('S09.9', 'Unspecified injury of head', 'Cedera kepala, tidak ditentukan', 'XIX', 'S00-S09', true),
('T07', 'Unspecified multiple injuries', 'Cedera ganda, tidak ditentukan', 'XIX', 'T00-T07', true),
('Z00.0', 'General medical examination', 'Pemeriksaan medis umum', 'XXI', 'Z00-Z13', true),
('Z01.2', 'Dental examination', 'Pemeriksaan gigi', 'XXI', 'Z00-Z13', true)
ON CONFLICT (icd10_code) DO UPDATE 
SET name_en = EXCLUDED.name_en, name_id = EXCLUDED.name_id, chapter_code = EXCLUDED.chapter_code, block_code = EXCLUDED.block_code, is_active = EXCLUDED.is_active;
