CREATE TABLE IF NOT EXISTS patients (
    mrn VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    nik VARCHAR(50) NOT NULL,
    dob VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
