// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
)

type Encounter struct {
	EncounterNo string
	Mrn         string
	Department  string
	DoctorID    string
	Status      string
	CreatedAt   sql.NullTime
}

type OutboxEvent struct {
	ID            string
	AggregateType string
	EventType     string
	Payload       json.RawMessage
	Status        string
	CreatedAt     sql.NullTime
}
