// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: shared/proto/pharmacy/v1/pharmacy.proto

package pharmacyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncounterNo   string                 `protobuf:"bytes,1,opt,name=encounter_no,json=encounterNo,proto3" json:"encounter_no,omitempty"`
	ItemCode      string                 `protobuf:"bytes,2,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrescribeRequest) Reset() {
	*x = PrescribeRequest{}
	mi := &file_shared_proto_pharmacy_v1_pharmacy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrescribeRequest) ProtoMessage() {}

func (x *PrescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_pharmacy_v1_pharmacy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrescribeRequest.ProtoReflect.Descriptor instead.
func (*PrescribeRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_pharmacy_v1_pharmacy_proto_rawDescGZIP(), []int{0}
}

func (x *PrescribeRequest) GetEncounterNo() string {
	if x != nil {
		return x.EncounterNo
	}
	return ""
}

func (x *PrescribeRequest) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *PrescribeRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type PrescribeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PrescriptionId string                 `protobuf:"bytes,2,opt,name=prescription_id,json=prescriptionId,proto3" json:"prescription_id,omitempty"`
	AmountToBill   float64                `protobuf:"fixed64,3,opt,name=amount_to_bill,json=amountToBill,proto3" json:"amount_to_bill,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrescribeResponse) Reset() {
	*x = PrescribeResponse{}
	mi := &file_shared_proto_pharmacy_v1_pharmacy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrescribeResponse) ProtoMessage() {}

func (x *PrescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_pharmacy_v1_pharmacy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrescribeResponse.ProtoReflect.Descriptor instead.
func (*PrescribeResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_pharmacy_v1_pharmacy_proto_rawDescGZIP(), []int{1}
}

func (x *PrescribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PrescribeResponse) GetPrescriptionId() string {
	if x != nil {
		return x.PrescriptionId
	}
	return ""
}

func (x *PrescribeResponse) GetAmountToBill() float64 {
	if x != nil {
		return x.AmountToBill
	}
	return 0
}

func (x *PrescribeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RollbackPrescriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrescriptionId string                 `protobuf:"bytes,1,opt,name=prescription_id,json=prescriptionId,proto3" json:"prescription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RollbackPrescriptionRequest) Reset() {
	*x = RollbackPrescriptionRequest{}
	mi := &file_shared_proto_pharmacy_v1_pharmacy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackPrescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackPrescriptionRequest) ProtoMessage() {}

func (x *RollbackPrescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_pharmacy_v1_pharmacy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackPrescriptionRequest.ProtoReflect.Descriptor instead.
func (*RollbackPrescriptionRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_pharmacy_v1_pharmacy_proto_rawDescGZIP(), []int{2}
}

func (x *RollbackPrescriptionRequest) GetPrescriptionId() string {
	if x != nil {
		return x.PrescriptionId
	}
	return ""
}

type RollbackPrescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackPrescriptionResponse) Reset() {
	*x = RollbackPrescriptionResponse{}
	mi := &file_shared_proto_pharmacy_v1_pharmacy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackPrescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackPrescriptionResponse) ProtoMessage() {}

func (x *RollbackPrescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_pharmacy_v1_pharmacy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackPrescriptionResponse.ProtoReflect.Descriptor instead.
func (*RollbackPrescriptionResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_pharmacy_v1_pharmacy_proto_rawDescGZIP(), []int{3}
}

func (x *RollbackPrescriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackPrescriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_shared_proto_pharmacy_v1_pharmacy_proto protoreflect.FileDescriptor

const file_shared_proto_pharmacy_v1_pharmacy_proto_rawDesc = "" +
	"\n" +
	"'shared/proto/pharmacy/v1/pharmacy.proto\x12\vpharmacy.v1\"n\n" +
	"\x10PrescribeRequest\x12!\n" +
	"\fencounter_no\x18\x01 \x01(\tR\vencounterNo\x12\x1b\n" +
	"\titem_code\x18\x02 \x01(\tR\bitemCode\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\x96\x01\n" +
	"\x11PrescribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fprescription_id\x18\x02 \x01(\tR\x0eprescriptionId\x12$\n" +
	"\x0eamount_to_bill\x18\x03 \x01(\x01R\famountToBill\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"F\n" +
	"\x1bRollbackPrescriptionRequest\x12'\n" +
	"\x0fprescription_id\x18\x01 \x01(\tR\x0eprescriptionId\"R\n" +
	"\x1cRollbackPrescriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xca\x01\n" +
	"\x0fPharmacyService\x12J\n" +
	"\tPrescribe\x12\x1d.pharmacy.v1.PrescribeRequest\x1a\x1e.pharmacy.v1.PrescribeResponse\x12k\n" +
	"\x14RollbackPrescription\x12(.pharmacy.v1.RollbackPrescriptionRequest\x1a).pharmacy.v1.RollbackPrescriptionResponseBJZHgithub.com/aliube/go-micro-simrs-one/shared/proto/pharmacy/v1;pharmacyv1b\x06proto3"

var (
	file_shared_proto_pharmacy_v1_pharmacy_proto_rawDescOnce sync.Once
	file_shared_proto_pharmacy_v1_pharmacy_proto_rawDescData []byte
)

func file_shared_proto_pharmacy_v1_pharmacy_proto_rawDescGZIP() []byte {
	file_shared_proto_pharmacy_v1_pharmacy_proto_rawDescOnce.Do(func() {
		file_shared_proto_pharmacy_v1_pharmacy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_pharmacy_v1_pharmacy_proto_rawDesc), len(file_shared_proto_pharmacy_v1_pharmacy_proto_rawDesc)))
	})
	return file_shared_proto_pharmacy_v1_pharmacy_proto_rawDescData
}

var file_shared_proto_pharmacy_v1_pharmacy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shared_proto_pharmacy_v1_pharmacy_proto_goTypes = []any{
	(*PrescribeRequest)(nil),             // 0: pharmacy.v1.PrescribeRequest
	(*PrescribeResponse)(nil),            // 1: pharmacy.v1.PrescribeResponse
	(*RollbackPrescriptionRequest)(nil),  // 2: pharmacy.v1.RollbackPrescriptionRequest
	(*RollbackPrescriptionResponse)(nil), // 3: pharmacy.v1.RollbackPrescriptionResponse
}
var file_shared_proto_pharmacy_v1_pharmacy_proto_depIdxs = []int32{
	0, // 0: pharmacy.v1.PharmacyService.Prescribe:input_type -> pharmacy.v1.PrescribeRequest
	2, // 1: pharmacy.v1.PharmacyService.RollbackPrescription:input_type -> pharmacy.v1.RollbackPrescriptionRequest
	1, // 2: pharmacy.v1.PharmacyService.Prescribe:output_type -> pharmacy.v1.PrescribeResponse
	3, // 3: pharmacy.v1.PharmacyService.RollbackPrescription:output_type -> pharmacy.v1.RollbackPrescriptionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_pharmacy_v1_pharmacy_proto_init() }
func file_shared_proto_pharmacy_v1_pharmacy_proto_init() {
	if File_shared_proto_pharmacy_v1_pharmacy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_pharmacy_v1_pharmacy_proto_rawDesc), len(file_shared_proto_pharmacy_v1_pharmacy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_pharmacy_v1_pharmacy_proto_goTypes,
		DependencyIndexes: file_shared_proto_pharmacy_v1_pharmacy_proto_depIdxs,
		MessageInfos:      file_shared_proto_pharmacy_v1_pharmacy_proto_msgTypes,
	}.Build()
	File_shared_proto_pharmacy_v1_pharmacy_proto = out.File
	file_shared_proto_pharmacy_v1_pharmacy_proto_goTypes = nil
	file_shared_proto_pharmacy_v1_pharmacy_proto_depIdxs = nil
}
