syntax = "proto3";

package pharmacy.v1;

option go_package = "github.com/aliube/go-micro-simrs-one/shared/proto/pharmacy/v1;pharmacyv1";

service PharmacyService {
  // Initiates prescription. Reserves stock (Lock).
  rpc Prescribe (PrescribeRequest) returns (PrescribeResponse);
  
  // Saga Compensation: Release reserved stock
  rpc RollbackPrescription (RollbackPrescriptionRequest) returns (RollbackPrescriptionResponse);
}

message PrescribeRequest {
  string encounter_no = 1;
  string item_code = 2;
  int32 quantity = 3;
}

message PrescribeResponse {
  bool success = 1;
  string prescription_id = 2;
  double amount_to_bill = 3;
  string message = 4;
}

message RollbackPrescriptionRequest {
  string prescription_id = 1;
}

message RollbackPrescriptionResponse {
  bool success = 1;
  string message = 2;
}
