// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: proto/emr/v1/emr.proto

package emrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 1. Triage (Perawat)
type SubmitTriageRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	EncounterNo            string                 `protobuf:"bytes,1,opt,name=encounter_no,json=encounterNo,proto3" json:"encounter_no,omitempty"`
	BloodPressureSystolic  int32                  `protobuf:"varint,2,opt,name=blood_pressure_systolic,json=bloodPressureSystolic,proto3" json:"blood_pressure_systolic,omitempty"`
	BloodPressureDiastolic int32                  `protobuf:"varint,3,opt,name=blood_pressure_diastolic,json=bloodPressureDiastolic,proto3" json:"blood_pressure_diastolic,omitempty"`
	Temperature            float64                `protobuf:"fixed64,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	HeartRate              int32                  `protobuf:"varint,5,opt,name=heart_rate,json=heartRate,proto3" json:"heart_rate,omitempty"`
	Notes                  string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SubmitTriageRequest) Reset() {
	*x = SubmitTriageRequest{}
	mi := &file_proto_emr_v1_emr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTriageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTriageRequest) ProtoMessage() {}

func (x *SubmitTriageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emr_v1_emr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTriageRequest.ProtoReflect.Descriptor instead.
func (*SubmitTriageRequest) Descriptor() ([]byte, []int) {
	return file_proto_emr_v1_emr_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitTriageRequest) GetEncounterNo() string {
	if x != nil {
		return x.EncounterNo
	}
	return ""
}

func (x *SubmitTriageRequest) GetBloodPressureSystolic() int32 {
	if x != nil {
		return x.BloodPressureSystolic
	}
	return 0
}

func (x *SubmitTriageRequest) GetBloodPressureDiastolic() int32 {
	if x != nil {
		return x.BloodPressureDiastolic
	}
	return 0
}

func (x *SubmitTriageRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SubmitTriageRequest) GetHeartRate() int32 {
	if x != nil {
		return x.HeartRate
	}
	return 0
}

func (x *SubmitTriageRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type SubmitTriageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTriageResponse) Reset() {
	*x = SubmitTriageResponse{}
	mi := &file_proto_emr_v1_emr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTriageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTriageResponse) ProtoMessage() {}

func (x *SubmitTriageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emr_v1_emr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTriageResponse.ProtoReflect.Descriptor instead.
func (*SubmitTriageResponse) Descriptor() ([]byte, []int) {
	return file_proto_emr_v1_emr_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitTriageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitTriageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 2. Diagnosis (Dokter)
type AddDiagnosisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncounterNo   string                 `protobuf:"bytes,1,opt,name=encounter_no,json=encounterNo,proto3" json:"encounter_no,omitempty"`
	Icd10Code     string                 `protobuf:"bytes,2,opt,name=icd10_code,json=icd10Code,proto3" json:"icd10_code,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDiagnosisRequest) Reset() {
	*x = AddDiagnosisRequest{}
	mi := &file_proto_emr_v1_emr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDiagnosisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDiagnosisRequest) ProtoMessage() {}

func (x *AddDiagnosisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emr_v1_emr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDiagnosisRequest.ProtoReflect.Descriptor instead.
func (*AddDiagnosisRequest) Descriptor() ([]byte, []int) {
	return file_proto_emr_v1_emr_proto_rawDescGZIP(), []int{2}
}

func (x *AddDiagnosisRequest) GetEncounterNo() string {
	if x != nil {
		return x.EncounterNo
	}
	return ""
}

func (x *AddDiagnosisRequest) GetIcd10Code() string {
	if x != nil {
		return x.Icd10Code
	}
	return ""
}

func (x *AddDiagnosisRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type AddDiagnosisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDiagnosisResponse) Reset() {
	*x = AddDiagnosisResponse{}
	mi := &file_proto_emr_v1_emr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDiagnosisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDiagnosisResponse) ProtoMessage() {}

func (x *AddDiagnosisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emr_v1_emr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDiagnosisResponse.ProtoReflect.Descriptor instead.
func (*AddDiagnosisResponse) Descriptor() ([]byte, []int) {
	return file_proto_emr_v1_emr_proto_rawDescGZIP(), []int{3}
}

func (x *AddDiagnosisResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddDiagnosisResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 3. Medical Action (Dokter)
type AddMedicalActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncounterNo   string                 `protobuf:"bytes,1,opt,name=encounter_no,json=encounterNo,proto3" json:"encounter_no,omitempty"`
	ActionCode    string                 `protobuf:"bytes,2,opt,name=action_code,json=actionCode,proto3" json:"action_code,omitempty"`
	ActionName    string                 `protobuf:"bytes,3,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMedicalActionRequest) Reset() {
	*x = AddMedicalActionRequest{}
	mi := &file_proto_emr_v1_emr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMedicalActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMedicalActionRequest) ProtoMessage() {}

func (x *AddMedicalActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emr_v1_emr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMedicalActionRequest.ProtoReflect.Descriptor instead.
func (*AddMedicalActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_emr_v1_emr_proto_rawDescGZIP(), []int{4}
}

func (x *AddMedicalActionRequest) GetEncounterNo() string {
	if x != nil {
		return x.EncounterNo
	}
	return ""
}

func (x *AddMedicalActionRequest) GetActionCode() string {
	if x != nil {
		return x.ActionCode
	}
	return ""
}

func (x *AddMedicalActionRequest) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *AddMedicalActionRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddMedicalActionRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type AddMedicalActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMedicalActionResponse) Reset() {
	*x = AddMedicalActionResponse{}
	mi := &file_proto_emr_v1_emr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMedicalActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMedicalActionResponse) ProtoMessage() {}

func (x *AddMedicalActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emr_v1_emr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMedicalActionResponse.ProtoReflect.Descriptor instead.
func (*AddMedicalActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_emr_v1_emr_proto_rawDescGZIP(), []int{5}
}

func (x *AddMedicalActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddMedicalActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 4. Get Record
type GetMedicalRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncounterNo   string                 `protobuf:"bytes,1,opt,name=encounter_no,json=encounterNo,proto3" json:"encounter_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMedicalRecordRequest) Reset() {
	*x = GetMedicalRecordRequest{}
	mi := &file_proto_emr_v1_emr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMedicalRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedicalRecordRequest) ProtoMessage() {}

func (x *GetMedicalRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emr_v1_emr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedicalRecordRequest.ProtoReflect.Descriptor instead.
func (*GetMedicalRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_emr_v1_emr_proto_rawDescGZIP(), []int{6}
}

func (x *GetMedicalRecordRequest) GetEncounterNo() string {
	if x != nil {
		return x.EncounterNo
	}
	return ""
}

type MedicalAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionCode    string                 `protobuf:"bytes,1,opt,name=action_code,json=actionCode,proto3" json:"action_code,omitempty"`
	ActionName    string                 `protobuf:"bytes,2,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MedicalAction) Reset() {
	*x = MedicalAction{}
	mi := &file_proto_emr_v1_emr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MedicalAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedicalAction) ProtoMessage() {}

func (x *MedicalAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emr_v1_emr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedicalAction.ProtoReflect.Descriptor instead.
func (*MedicalAction) Descriptor() ([]byte, []int) {
	return file_proto_emr_v1_emr_proto_rawDescGZIP(), []int{7}
}

func (x *MedicalAction) GetActionCode() string {
	if x != nil {
		return x.ActionCode
	}
	return ""
}

func (x *MedicalAction) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *MedicalAction) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type TriageData struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	BloodPressureSystolic  int32                  `protobuf:"varint,1,opt,name=blood_pressure_systolic,json=bloodPressureSystolic,proto3" json:"blood_pressure_systolic,omitempty"`
	BloodPressureDiastolic int32                  `protobuf:"varint,2,opt,name=blood_pressure_diastolic,json=bloodPressureDiastolic,proto3" json:"blood_pressure_diastolic,omitempty"`
	Temperature            float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	HeartRate              int32                  `protobuf:"varint,4,opt,name=heart_rate,json=heartRate,proto3" json:"heart_rate,omitempty"`
	Notes                  string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TriageData) Reset() {
	*x = TriageData{}
	mi := &file_proto_emr_v1_emr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriageData) ProtoMessage() {}

func (x *TriageData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emr_v1_emr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriageData.ProtoReflect.Descriptor instead.
func (*TriageData) Descriptor() ([]byte, []int) {
	return file_proto_emr_v1_emr_proto_rawDescGZIP(), []int{8}
}

func (x *TriageData) GetBloodPressureSystolic() int32 {
	if x != nil {
		return x.BloodPressureSystolic
	}
	return 0
}

func (x *TriageData) GetBloodPressureDiastolic() int32 {
	if x != nil {
		return x.BloodPressureDiastolic
	}
	return 0
}

func (x *TriageData) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *TriageData) GetHeartRate() int32 {
	if x != nil {
		return x.HeartRate
	}
	return 0
}

func (x *TriageData) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type GetMedicalRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncounterNo   string                 `protobuf:"bytes,1,opt,name=encounter_no,json=encounterNo,proto3" json:"encounter_no,omitempty"`
	PatientMrn    string                 `protobuf:"bytes,2,opt,name=patient_mrn,json=patientMrn,proto3" json:"patient_mrn,omitempty"`
	Triage        *TriageData            `protobuf:"bytes,3,opt,name=triage,proto3" json:"triage,omitempty"`
	Icd10Codes    []string               `protobuf:"bytes,4,rep,name=icd10_codes,json=icd10Codes,proto3" json:"icd10_codes,omitempty"`
	Actions       []*MedicalAction       `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	Notes         string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMedicalRecordResponse) Reset() {
	*x = GetMedicalRecordResponse{}
	mi := &file_proto_emr_v1_emr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMedicalRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedicalRecordResponse) ProtoMessage() {}

func (x *GetMedicalRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emr_v1_emr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedicalRecordResponse.ProtoReflect.Descriptor instead.
func (*GetMedicalRecordResponse) Descriptor() ([]byte, []int) {
	return file_proto_emr_v1_emr_proto_rawDescGZIP(), []int{9}
}

func (x *GetMedicalRecordResponse) GetEncounterNo() string {
	if x != nil {
		return x.EncounterNo
	}
	return ""
}

func (x *GetMedicalRecordResponse) GetPatientMrn() string {
	if x != nil {
		return x.PatientMrn
	}
	return ""
}

func (x *GetMedicalRecordResponse) GetTriage() *TriageData {
	if x != nil {
		return x.Triage
	}
	return nil
}

func (x *GetMedicalRecordResponse) GetIcd10Codes() []string {
	if x != nil {
		return x.Icd10Codes
	}
	return nil
}

func (x *GetMedicalRecordResponse) GetActions() []*MedicalAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *GetMedicalRecordResponse) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

var File_proto_emr_v1_emr_proto protoreflect.FileDescriptor

const file_proto_emr_v1_emr_proto_rawDesc = "" +
	"\n" +
	"\x16proto/emr/v1/emr.proto\x12\x06emr.v1\"\x81\x02\n" +
	"\x13SubmitTriageRequest\x12!\n" +
	"\fencounter_no\x18\x01 \x01(\tR\vencounterNo\x126\n" +
	"\x17blood_pressure_systolic\x18\x02 \x01(\x05R\x15bloodPressureSystolic\x128\n" +
	"\x18blood_pressure_diastolic\x18\x03 \x01(\x05R\x16bloodPressureDiastolic\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"heart_rate\x18\x05 \x01(\x05R\theartRate\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\"J\n" +
	"\x14SubmitTriageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"m\n" +
	"\x13AddDiagnosisRequest\x12!\n" +
	"\fencounter_no\x18\x01 \x01(\tR\vencounterNo\x12\x1d\n" +
	"\n" +
	"icd10_code\x18\x02 \x01(\tR\ticd10Code\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\"J\n" +
	"\x14AddDiagnosisResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xaa\x01\n" +
	"\x17AddMedicalActionRequest\x12!\n" +
	"\fencounter_no\x18\x01 \x01(\tR\vencounterNo\x12\x1f\n" +
	"\vaction_code\x18\x02 \x01(\tR\n" +
	"actionCode\x12\x1f\n" +
	"\vaction_name\x18\x03 \x01(\tR\n" +
	"actionName\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"N\n" +
	"\x18AddMedicalActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"<\n" +
	"\x17GetMedicalRecordRequest\x12!\n" +
	"\fencounter_no\x18\x01 \x01(\tR\vencounterNo\"g\n" +
	"\rMedicalAction\x12\x1f\n" +
	"\vaction_code\x18\x01 \x01(\tR\n" +
	"actionCode\x12\x1f\n" +
	"\vaction_name\x18\x02 \x01(\tR\n" +
	"actionName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"\xd5\x01\n" +
	"\n" +
	"TriageData\x126\n" +
	"\x17blood_pressure_systolic\x18\x01 \x01(\x05R\x15bloodPressureSystolic\x128\n" +
	"\x18blood_pressure_diastolic\x18\x02 \x01(\x05R\x16bloodPressureDiastolic\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"heart_rate\x18\x04 \x01(\x05R\theartRate\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"\xf2\x01\n" +
	"\x18GetMedicalRecordResponse\x12!\n" +
	"\fencounter_no\x18\x01 \x01(\tR\vencounterNo\x12\x1f\n" +
	"\vpatient_mrn\x18\x02 \x01(\tR\n" +
	"patientMrn\x12*\n" +
	"\x06triage\x18\x03 \x01(\v2\x12.emr.v1.TriageDataR\x06triage\x12\x1f\n" +
	"\vicd10_codes\x18\x04 \x03(\tR\n" +
	"icd10Codes\x12/\n" +
	"\aactions\x18\x05 \x03(\v2\x15.emr.v1.MedicalActionR\aactions\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes2\xd0\x02\n" +
	"\n" +
	"EMRService\x12I\n" +
	"\fSubmitTriage\x12\x1b.emr.v1.SubmitTriageRequest\x1a\x1c.emr.v1.SubmitTriageResponse\x12I\n" +
	"\fAddDiagnosis\x12\x1b.emr.v1.AddDiagnosisRequest\x1a\x1c.emr.v1.AddDiagnosisResponse\x12U\n" +
	"\x10AddMedicalAction\x12\x1f.emr.v1.AddMedicalActionRequest\x1a .emr.v1.AddMedicalActionResponse\x12U\n" +
	"\x10GetMedicalRecord\x12\x1f.emr.v1.GetMedicalRecordRequest\x1a .emr.v1.GetMedicalRecordResponseB@Z>github.com/aliube/go-micro-simrs-one/shared/proto/emr/v1;emrv1b\x06proto3"

var (
	file_proto_emr_v1_emr_proto_rawDescOnce sync.Once
	file_proto_emr_v1_emr_proto_rawDescData []byte
)

func file_proto_emr_v1_emr_proto_rawDescGZIP() []byte {
	file_proto_emr_v1_emr_proto_rawDescOnce.Do(func() {
		file_proto_emr_v1_emr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_emr_v1_emr_proto_rawDesc), len(file_proto_emr_v1_emr_proto_rawDesc)))
	})
	return file_proto_emr_v1_emr_proto_rawDescData
}

var file_proto_emr_v1_emr_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_emr_v1_emr_proto_goTypes = []any{
	(*SubmitTriageRequest)(nil),      // 0: emr.v1.SubmitTriageRequest
	(*SubmitTriageResponse)(nil),     // 1: emr.v1.SubmitTriageResponse
	(*AddDiagnosisRequest)(nil),      // 2: emr.v1.AddDiagnosisRequest
	(*AddDiagnosisResponse)(nil),     // 3: emr.v1.AddDiagnosisResponse
	(*AddMedicalActionRequest)(nil),  // 4: emr.v1.AddMedicalActionRequest
	(*AddMedicalActionResponse)(nil), // 5: emr.v1.AddMedicalActionResponse
	(*GetMedicalRecordRequest)(nil),  // 6: emr.v1.GetMedicalRecordRequest
	(*MedicalAction)(nil),            // 7: emr.v1.MedicalAction
	(*TriageData)(nil),               // 8: emr.v1.TriageData
	(*GetMedicalRecordResponse)(nil), // 9: emr.v1.GetMedicalRecordResponse
}
var file_proto_emr_v1_emr_proto_depIdxs = []int32{
	8, // 0: emr.v1.GetMedicalRecordResponse.triage:type_name -> emr.v1.TriageData
	7, // 1: emr.v1.GetMedicalRecordResponse.actions:type_name -> emr.v1.MedicalAction
	0, // 2: emr.v1.EMRService.SubmitTriage:input_type -> emr.v1.SubmitTriageRequest
	2, // 3: emr.v1.EMRService.AddDiagnosis:input_type -> emr.v1.AddDiagnosisRequest
	4, // 4: emr.v1.EMRService.AddMedicalAction:input_type -> emr.v1.AddMedicalActionRequest
	6, // 5: emr.v1.EMRService.GetMedicalRecord:input_type -> emr.v1.GetMedicalRecordRequest
	1, // 6: emr.v1.EMRService.SubmitTriage:output_type -> emr.v1.SubmitTriageResponse
	3, // 7: emr.v1.EMRService.AddDiagnosis:output_type -> emr.v1.AddDiagnosisResponse
	5, // 8: emr.v1.EMRService.AddMedicalAction:output_type -> emr.v1.AddMedicalActionResponse
	9, // 9: emr.v1.EMRService.GetMedicalRecord:output_type -> emr.v1.GetMedicalRecordResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_emr_v1_emr_proto_init() }
func file_proto_emr_v1_emr_proto_init() {
	if File_proto_emr_v1_emr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_emr_v1_emr_proto_rawDesc), len(file_proto_emr_v1_emr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_emr_v1_emr_proto_goTypes,
		DependencyIndexes: file_proto_emr_v1_emr_proto_depIdxs,
		MessageInfos:      file_proto_emr_v1_emr_proto_msgTypes,
	}.Build()
	File_proto_emr_v1_emr_proto = out.File
	file_proto_emr_v1_emr_proto_goTypes = nil
	file_proto_emr_v1_emr_proto_depIdxs = nil
}
