// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.26.1
// source: emr/v1/emr.proto

package emrv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EMRService_SubmitTriage_FullMethodName                  = "/emr.v1.EMRService/SubmitTriage"
	EMRService_AddMedicalAction_FullMethodName              = "/emr.v1.EMRService/AddMedicalAction"
	EMRService_GetMedicalRecord_FullMethodName              = "/emr.v1.EMRService/GetMedicalRecord"
	EMRService_StartEncounter_FullMethodName                = "/emr.v1.EMRService/StartEncounter"
	EMRService_GetEstimatedWaitTime_FullMethodName          = "/emr.v1.EMRService/GetEstimatedWaitTime"
	EMRService_GetPolyclinics_FullMethodName                = "/emr.v1.EMRService/GetPolyclinics"
	EMRService_GetMasterKBMs_FullMethodName                 = "/emr.v1.EMRService/GetMasterKBMs"
	EMRService_GetMasterKBMsByPoli_FullMethodName           = "/emr.v1.EMRService/GetMasterKBMsByPoli"
	EMRService_GetMasterTindakan_FullMethodName             = "/emr.v1.EMRService/GetMasterTindakan"
	EMRService_GetMasterTindakanByPoli_FullMethodName       = "/emr.v1.EMRService/GetMasterTindakanByPoli"
	EMRService_GetMasterICD10_FullMethodName                = "/emr.v1.EMRService/GetMasterICD10"
	EMRService_GetMasterICD10ByPoli_FullMethodName          = "/emr.v1.EMRService/GetMasterICD10ByPoli"
	EMRService_SearchKBM_FullMethodName                     = "/emr.v1.EMRService/SearchKBM"
	EMRService_GetKBMDetail_FullMethodName                  = "/emr.v1.EMRService/GetKBMDetail"
	EMRService_GetICD10SuggestionsForKBM_FullMethodName     = "/emr.v1.EMRService/GetICD10SuggestionsForKBM"
	EMRService_AddDiagnosisKBM_FullMethodName               = "/emr.v1.EMRService/AddDiagnosisKBM"
	EMRService_VerifyICD10Mapping_FullMethodName            = "/emr.v1.EMRService/VerifyICD10Mapping"
	EMRService_ListPendingICD10Verifications_FullMethodName = "/emr.v1.EMRService/ListPendingICD10Verifications"
)

// EMRServiceClient is the client API for EMRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EMRServiceClient interface {
	SubmitTriage(ctx context.Context, in *SubmitTriageRequest, opts ...grpc.CallOption) (*SubmitTriageResponse, error)
	AddMedicalAction(ctx context.Context, in *AddMedicalActionRequest, opts ...grpc.CallOption) (*AddMedicalActionResponse, error)
	GetMedicalRecord(ctx context.Context, in *GetMedicalRecordRequest, opts ...grpc.CallOption) (*GetMedicalRecordResponse, error)
	StartEncounter(ctx context.Context, in *StartEncounterRequest, opts ...grpc.CallOption) (*StartEncounterResponse, error)
	GetEstimatedWaitTime(ctx context.Context, in *GetEstimatedWaitTimeRequest, opts ...grpc.CallOption) (*GetEstimatedWaitTimeResponse, error)
	// Master Data Reads
	GetPolyclinics(ctx context.Context, in *GetPolyclinicsRequest, opts ...grpc.CallOption) (*GetPolyclinicsResponse, error)
	GetMasterKBMs(ctx context.Context, in *GetMasterKBMsRequest, opts ...grpc.CallOption) (*GetMasterKBMsResponse, error)
	GetMasterKBMsByPoli(ctx context.Context, in *GetMasterKBMsByPoliRequest, opts ...grpc.CallOption) (*GetMasterKBMsByPoliResponse, error)
	GetMasterTindakan(ctx context.Context, in *GetMasterTindakanRequest, opts ...grpc.CallOption) (*GetMasterTindakanResponse, error)
	GetMasterTindakanByPoli(ctx context.Context, in *GetMasterTindakanByPoliRequest, opts ...grpc.CallOption) (*GetMasterTindakanByPoliResponse, error)
	GetMasterICD10(ctx context.Context, in *GetMasterICD10Request, opts ...grpc.CallOption) (*GetMasterICD10Response, error)
	GetMasterICD10ByPoli(ctx context.Context, in *GetMasterICD10ByPoliRequest, opts ...grpc.CallOption) (*GetMasterICD10ByPoliResponse, error)
	// Master KBM (Existing)
	SearchKBM(ctx context.Context, in *SearchKBMRequest, opts ...grpc.CallOption) (*SearchKBMResponse, error)
	GetKBMDetail(ctx context.Context, in *GetKBMDetailRequest, opts ...grpc.CallOption) (*GetKBMDetailResponse, error)
	GetICD10SuggestionsForKBM(ctx context.Context, in *GetICD10SuggestionsForKBMRequest, opts ...grpc.CallOption) (*GetICD10SuggestionsForKBMResponse, error)
	// Diagnosis (Dokter - Poliklinik)
	AddDiagnosisKBM(ctx context.Context, in *AddDiagnosisKBMRequest, opts ...grpc.CallOption) (*AddDiagnosisKBMResponse, error)
	// Verifikasi ICD-10 (Bagian Rekam Medis)
	VerifyICD10Mapping(ctx context.Context, in *VerifyICD10MappingRequest, opts ...grpc.CallOption) (*VerifyICD10MappingResponse, error)
	ListPendingICD10Verifications(ctx context.Context, in *ListPendingICD10VerificationsRequest, opts ...grpc.CallOption) (*ListPendingICD10VerificationsResponse, error)
}

type eMRServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEMRServiceClient(cc grpc.ClientConnInterface) EMRServiceClient {
	return &eMRServiceClient{cc}
}

func (c *eMRServiceClient) SubmitTriage(ctx context.Context, in *SubmitTriageRequest, opts ...grpc.CallOption) (*SubmitTriageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTriageResponse)
	err := c.cc.Invoke(ctx, EMRService_SubmitTriage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) AddMedicalAction(ctx context.Context, in *AddMedicalActionRequest, opts ...grpc.CallOption) (*AddMedicalActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMedicalActionResponse)
	err := c.cc.Invoke(ctx, EMRService_AddMedicalAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) GetMedicalRecord(ctx context.Context, in *GetMedicalRecordRequest, opts ...grpc.CallOption) (*GetMedicalRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMedicalRecordResponse)
	err := c.cc.Invoke(ctx, EMRService_GetMedicalRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) StartEncounter(ctx context.Context, in *StartEncounterRequest, opts ...grpc.CallOption) (*StartEncounterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartEncounterResponse)
	err := c.cc.Invoke(ctx, EMRService_StartEncounter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) GetEstimatedWaitTime(ctx context.Context, in *GetEstimatedWaitTimeRequest, opts ...grpc.CallOption) (*GetEstimatedWaitTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEstimatedWaitTimeResponse)
	err := c.cc.Invoke(ctx, EMRService_GetEstimatedWaitTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) GetPolyclinics(ctx context.Context, in *GetPolyclinicsRequest, opts ...grpc.CallOption) (*GetPolyclinicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPolyclinicsResponse)
	err := c.cc.Invoke(ctx, EMRService_GetPolyclinics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) GetMasterKBMs(ctx context.Context, in *GetMasterKBMsRequest, opts ...grpc.CallOption) (*GetMasterKBMsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMasterKBMsResponse)
	err := c.cc.Invoke(ctx, EMRService_GetMasterKBMs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) GetMasterKBMsByPoli(ctx context.Context, in *GetMasterKBMsByPoliRequest, opts ...grpc.CallOption) (*GetMasterKBMsByPoliResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMasterKBMsByPoliResponse)
	err := c.cc.Invoke(ctx, EMRService_GetMasterKBMsByPoli_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) GetMasterTindakan(ctx context.Context, in *GetMasterTindakanRequest, opts ...grpc.CallOption) (*GetMasterTindakanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMasterTindakanResponse)
	err := c.cc.Invoke(ctx, EMRService_GetMasterTindakan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) GetMasterTindakanByPoli(ctx context.Context, in *GetMasterTindakanByPoliRequest, opts ...grpc.CallOption) (*GetMasterTindakanByPoliResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMasterTindakanByPoliResponse)
	err := c.cc.Invoke(ctx, EMRService_GetMasterTindakanByPoli_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) GetMasterICD10(ctx context.Context, in *GetMasterICD10Request, opts ...grpc.CallOption) (*GetMasterICD10Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMasterICD10Response)
	err := c.cc.Invoke(ctx, EMRService_GetMasterICD10_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) GetMasterICD10ByPoli(ctx context.Context, in *GetMasterICD10ByPoliRequest, opts ...grpc.CallOption) (*GetMasterICD10ByPoliResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMasterICD10ByPoliResponse)
	err := c.cc.Invoke(ctx, EMRService_GetMasterICD10ByPoli_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) SearchKBM(ctx context.Context, in *SearchKBMRequest, opts ...grpc.CallOption) (*SearchKBMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchKBMResponse)
	err := c.cc.Invoke(ctx, EMRService_SearchKBM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) GetKBMDetail(ctx context.Context, in *GetKBMDetailRequest, opts ...grpc.CallOption) (*GetKBMDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKBMDetailResponse)
	err := c.cc.Invoke(ctx, EMRService_GetKBMDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) GetICD10SuggestionsForKBM(ctx context.Context, in *GetICD10SuggestionsForKBMRequest, opts ...grpc.CallOption) (*GetICD10SuggestionsForKBMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetICD10SuggestionsForKBMResponse)
	err := c.cc.Invoke(ctx, EMRService_GetICD10SuggestionsForKBM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) AddDiagnosisKBM(ctx context.Context, in *AddDiagnosisKBMRequest, opts ...grpc.CallOption) (*AddDiagnosisKBMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDiagnosisKBMResponse)
	err := c.cc.Invoke(ctx, EMRService_AddDiagnosisKBM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) VerifyICD10Mapping(ctx context.Context, in *VerifyICD10MappingRequest, opts ...grpc.CallOption) (*VerifyICD10MappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyICD10MappingResponse)
	err := c.cc.Invoke(ctx, EMRService_VerifyICD10Mapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) ListPendingICD10Verifications(ctx context.Context, in *ListPendingICD10VerificationsRequest, opts ...grpc.CallOption) (*ListPendingICD10VerificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingICD10VerificationsResponse)
	err := c.cc.Invoke(ctx, EMRService_ListPendingICD10Verifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EMRServiceServer is the server API for EMRService service.
// All implementations must embed UnimplementedEMRServiceServer
// for forward compatibility.
type EMRServiceServer interface {
	SubmitTriage(context.Context, *SubmitTriageRequest) (*SubmitTriageResponse, error)
	AddMedicalAction(context.Context, *AddMedicalActionRequest) (*AddMedicalActionResponse, error)
	GetMedicalRecord(context.Context, *GetMedicalRecordRequest) (*GetMedicalRecordResponse, error)
	StartEncounter(context.Context, *StartEncounterRequest) (*StartEncounterResponse, error)
	GetEstimatedWaitTime(context.Context, *GetEstimatedWaitTimeRequest) (*GetEstimatedWaitTimeResponse, error)
	// Master Data Reads
	GetPolyclinics(context.Context, *GetPolyclinicsRequest) (*GetPolyclinicsResponse, error)
	GetMasterKBMs(context.Context, *GetMasterKBMsRequest) (*GetMasterKBMsResponse, error)
	GetMasterKBMsByPoli(context.Context, *GetMasterKBMsByPoliRequest) (*GetMasterKBMsByPoliResponse, error)
	GetMasterTindakan(context.Context, *GetMasterTindakanRequest) (*GetMasterTindakanResponse, error)
	GetMasterTindakanByPoli(context.Context, *GetMasterTindakanByPoliRequest) (*GetMasterTindakanByPoliResponse, error)
	GetMasterICD10(context.Context, *GetMasterICD10Request) (*GetMasterICD10Response, error)
	GetMasterICD10ByPoli(context.Context, *GetMasterICD10ByPoliRequest) (*GetMasterICD10ByPoliResponse, error)
	// Master KBM (Existing)
	SearchKBM(context.Context, *SearchKBMRequest) (*SearchKBMResponse, error)
	GetKBMDetail(context.Context, *GetKBMDetailRequest) (*GetKBMDetailResponse, error)
	GetICD10SuggestionsForKBM(context.Context, *GetICD10SuggestionsForKBMRequest) (*GetICD10SuggestionsForKBMResponse, error)
	// Diagnosis (Dokter - Poliklinik)
	AddDiagnosisKBM(context.Context, *AddDiagnosisKBMRequest) (*AddDiagnosisKBMResponse, error)
	// Verifikasi ICD-10 (Bagian Rekam Medis)
	VerifyICD10Mapping(context.Context, *VerifyICD10MappingRequest) (*VerifyICD10MappingResponse, error)
	ListPendingICD10Verifications(context.Context, *ListPendingICD10VerificationsRequest) (*ListPendingICD10VerificationsResponse, error)
	mustEmbedUnimplementedEMRServiceServer()
}

// UnimplementedEMRServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEMRServiceServer struct{}

func (UnimplementedEMRServiceServer) SubmitTriage(context.Context, *SubmitTriageRequest) (*SubmitTriageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTriage not implemented")
}
func (UnimplementedEMRServiceServer) AddMedicalAction(context.Context, *AddMedicalActionRequest) (*AddMedicalActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMedicalAction not implemented")
}
func (UnimplementedEMRServiceServer) GetMedicalRecord(context.Context, *GetMedicalRecordRequest) (*GetMedicalRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMedicalRecord not implemented")
}
func (UnimplementedEMRServiceServer) StartEncounter(context.Context, *StartEncounterRequest) (*StartEncounterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartEncounter not implemented")
}
func (UnimplementedEMRServiceServer) GetEstimatedWaitTime(context.Context, *GetEstimatedWaitTimeRequest) (*GetEstimatedWaitTimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEstimatedWaitTime not implemented")
}
func (UnimplementedEMRServiceServer) GetPolyclinics(context.Context, *GetPolyclinicsRequest) (*GetPolyclinicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolyclinics not implemented")
}
func (UnimplementedEMRServiceServer) GetMasterKBMs(context.Context, *GetMasterKBMsRequest) (*GetMasterKBMsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMasterKBMs not implemented")
}
func (UnimplementedEMRServiceServer) GetMasterKBMsByPoli(context.Context, *GetMasterKBMsByPoliRequest) (*GetMasterKBMsByPoliResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMasterKBMsByPoli not implemented")
}
func (UnimplementedEMRServiceServer) GetMasterTindakan(context.Context, *GetMasterTindakanRequest) (*GetMasterTindakanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMasterTindakan not implemented")
}
func (UnimplementedEMRServiceServer) GetMasterTindakanByPoli(context.Context, *GetMasterTindakanByPoliRequest) (*GetMasterTindakanByPoliResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMasterTindakanByPoli not implemented")
}
func (UnimplementedEMRServiceServer) GetMasterICD10(context.Context, *GetMasterICD10Request) (*GetMasterICD10Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMasterICD10 not implemented")
}
func (UnimplementedEMRServiceServer) GetMasterICD10ByPoli(context.Context, *GetMasterICD10ByPoliRequest) (*GetMasterICD10ByPoliResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMasterICD10ByPoli not implemented")
}
func (UnimplementedEMRServiceServer) SearchKBM(context.Context, *SearchKBMRequest) (*SearchKBMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchKBM not implemented")
}
func (UnimplementedEMRServiceServer) GetKBMDetail(context.Context, *GetKBMDetailRequest) (*GetKBMDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKBMDetail not implemented")
}
func (UnimplementedEMRServiceServer) GetICD10SuggestionsForKBM(context.Context, *GetICD10SuggestionsForKBMRequest) (*GetICD10SuggestionsForKBMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetICD10SuggestionsForKBM not implemented")
}
func (UnimplementedEMRServiceServer) AddDiagnosisKBM(context.Context, *AddDiagnosisKBMRequest) (*AddDiagnosisKBMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDiagnosisKBM not implemented")
}
func (UnimplementedEMRServiceServer) VerifyICD10Mapping(context.Context, *VerifyICD10MappingRequest) (*VerifyICD10MappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyICD10Mapping not implemented")
}
func (UnimplementedEMRServiceServer) ListPendingICD10Verifications(context.Context, *ListPendingICD10VerificationsRequest) (*ListPendingICD10VerificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingICD10Verifications not implemented")
}
func (UnimplementedEMRServiceServer) mustEmbedUnimplementedEMRServiceServer() {}
func (UnimplementedEMRServiceServer) testEmbeddedByValue()                    {}

// UnsafeEMRServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EMRServiceServer will
// result in compilation errors.
type UnsafeEMRServiceServer interface {
	mustEmbedUnimplementedEMRServiceServer()
}

func RegisterEMRServiceServer(s grpc.ServiceRegistrar, srv EMRServiceServer) {
	// If the following call panics, it indicates UnimplementedEMRServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EMRService_ServiceDesc, srv)
}

func _EMRService_SubmitTriage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTriageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).SubmitTriage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_SubmitTriage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).SubmitTriage(ctx, req.(*SubmitTriageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_AddMedicalAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMedicalActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).AddMedicalAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_AddMedicalAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).AddMedicalAction(ctx, req.(*AddMedicalActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_GetMedicalRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMedicalRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).GetMedicalRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_GetMedicalRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).GetMedicalRecord(ctx, req.(*GetMedicalRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_StartEncounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartEncounterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).StartEncounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_StartEncounter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).StartEncounter(ctx, req.(*StartEncounterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_GetEstimatedWaitTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEstimatedWaitTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).GetEstimatedWaitTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_GetEstimatedWaitTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).GetEstimatedWaitTime(ctx, req.(*GetEstimatedWaitTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_GetPolyclinics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolyclinicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).GetPolyclinics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_GetPolyclinics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).GetPolyclinics(ctx, req.(*GetPolyclinicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_GetMasterKBMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMasterKBMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).GetMasterKBMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_GetMasterKBMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).GetMasterKBMs(ctx, req.(*GetMasterKBMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_GetMasterKBMsByPoli_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMasterKBMsByPoliRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).GetMasterKBMsByPoli(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_GetMasterKBMsByPoli_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).GetMasterKBMsByPoli(ctx, req.(*GetMasterKBMsByPoliRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_GetMasterTindakan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMasterTindakanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).GetMasterTindakan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_GetMasterTindakan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).GetMasterTindakan(ctx, req.(*GetMasterTindakanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_GetMasterTindakanByPoli_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMasterTindakanByPoliRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).GetMasterTindakanByPoli(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_GetMasterTindakanByPoli_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).GetMasterTindakanByPoli(ctx, req.(*GetMasterTindakanByPoliRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_GetMasterICD10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMasterICD10Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).GetMasterICD10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_GetMasterICD10_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).GetMasterICD10(ctx, req.(*GetMasterICD10Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_GetMasterICD10ByPoli_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMasterICD10ByPoliRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).GetMasterICD10ByPoli(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_GetMasterICD10ByPoli_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).GetMasterICD10ByPoli(ctx, req.(*GetMasterICD10ByPoliRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_SearchKBM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchKBMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).SearchKBM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_SearchKBM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).SearchKBM(ctx, req.(*SearchKBMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_GetKBMDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKBMDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).GetKBMDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_GetKBMDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).GetKBMDetail(ctx, req.(*GetKBMDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_GetICD10SuggestionsForKBM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetICD10SuggestionsForKBMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).GetICD10SuggestionsForKBM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_GetICD10SuggestionsForKBM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).GetICD10SuggestionsForKBM(ctx, req.(*GetICD10SuggestionsForKBMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_AddDiagnosisKBM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDiagnosisKBMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).AddDiagnosisKBM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_AddDiagnosisKBM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).AddDiagnosisKBM(ctx, req.(*AddDiagnosisKBMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_VerifyICD10Mapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyICD10MappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).VerifyICD10Mapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_VerifyICD10Mapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).VerifyICD10Mapping(ctx, req.(*VerifyICD10MappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_ListPendingICD10Verifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingICD10VerificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).ListPendingICD10Verifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_ListPendingICD10Verifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).ListPendingICD10Verifications(ctx, req.(*ListPendingICD10VerificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EMRService_ServiceDesc is the grpc.ServiceDesc for EMRService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EMRService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emr.v1.EMRService",
	HandlerType: (*EMRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTriage",
			Handler:    _EMRService_SubmitTriage_Handler,
		},
		{
			MethodName: "AddMedicalAction",
			Handler:    _EMRService_AddMedicalAction_Handler,
		},
		{
			MethodName: "GetMedicalRecord",
			Handler:    _EMRService_GetMedicalRecord_Handler,
		},
		{
			MethodName: "StartEncounter",
			Handler:    _EMRService_StartEncounter_Handler,
		},
		{
			MethodName: "GetEstimatedWaitTime",
			Handler:    _EMRService_GetEstimatedWaitTime_Handler,
		},
		{
			MethodName: "GetPolyclinics",
			Handler:    _EMRService_GetPolyclinics_Handler,
		},
		{
			MethodName: "GetMasterKBMs",
			Handler:    _EMRService_GetMasterKBMs_Handler,
		},
		{
			MethodName: "GetMasterKBMsByPoli",
			Handler:    _EMRService_GetMasterKBMsByPoli_Handler,
		},
		{
			MethodName: "GetMasterTindakan",
			Handler:    _EMRService_GetMasterTindakan_Handler,
		},
		{
			MethodName: "GetMasterTindakanByPoli",
			Handler:    _EMRService_GetMasterTindakanByPoli_Handler,
		},
		{
			MethodName: "GetMasterICD10",
			Handler:    _EMRService_GetMasterICD10_Handler,
		},
		{
			MethodName: "GetMasterICD10ByPoli",
			Handler:    _EMRService_GetMasterICD10ByPoli_Handler,
		},
		{
			MethodName: "SearchKBM",
			Handler:    _EMRService_SearchKBM_Handler,
		},
		{
			MethodName: "GetKBMDetail",
			Handler:    _EMRService_GetKBMDetail_Handler,
		},
		{
			MethodName: "GetICD10SuggestionsForKBM",
			Handler:    _EMRService_GetICD10SuggestionsForKBM_Handler,
		},
		{
			MethodName: "AddDiagnosisKBM",
			Handler:    _EMRService_AddDiagnosisKBM_Handler,
		},
		{
			MethodName: "VerifyICD10Mapping",
			Handler:    _EMRService_VerifyICD10Mapping_Handler,
		},
		{
			MethodName: "ListPendingICD10Verifications",
			Handler:    _EMRService_ListPendingICD10Verifications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emr/v1/emr.proto",
}
