// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
)

type Inventory struct {
	ItemCode      string
	Name          string
	StockQuantity int32
	Price         string
}

type OutboxEvent struct {
	ID            string
	AggregateType string
	EventType     string
	Payload       json.RawMessage
	Status        string
	CreatedAt     sql.NullTime
}

type Prescription struct {
	ID           string
	EncounterNo  string
	Status       string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	IsCompounded sql.NullBool
	Notes        sql.NullString
}

type PrescriptionItem struct {
	ID             string
	PrescriptionID string
	ItemCode       string
	Quantity       int32
	Price          string
}
