// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (id, aggregate_type, event_type, payload, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, aggregate_type, event_type, payload, status, created_at
`

type CreateOutboxEventParams struct {
	ID            string
	AggregateType string
	EventType     string
	Payload       json.RawMessage
	Status        string
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRowContext(ctx, createOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.EventType,
		arg.Payload,
		arg.Status,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createPrescription = `-- name: CreatePrescription :one
INSERT INTO prescriptions (id, encounter_no, status, is_compounded, notes, diagnosis, gender, age_bracket, doctor_id, department_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, encounter_no, status, created_at, updated_at, is_compounded, notes, diagnosis, gender, age_bracket, doctor_id, department_code
`

type CreatePrescriptionParams struct {
	ID             string
	EncounterNo    string
	Status         string
	IsCompounded   sql.NullBool
	Notes          sql.NullString
	Diagnosis      sql.NullString
	Gender         sql.NullString
	AgeBracket     sql.NullString
	DoctorID       sql.NullString
	DepartmentCode sql.NullString
}

func (q *Queries) CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (Prescription, error) {
	row := q.db.QueryRowContext(ctx, createPrescription,
		arg.ID,
		arg.EncounterNo,
		arg.Status,
		arg.IsCompounded,
		arg.Notes,
		arg.Diagnosis,
		arg.Gender,
		arg.AgeBracket,
		arg.DoctorID,
		arg.DepartmentCode,
	)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.EncounterNo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsCompounded,
		&i.Notes,
		&i.Diagnosis,
		&i.Gender,
		&i.AgeBracket,
		&i.DoctorID,
		&i.DepartmentCode,
	)
	return i, err
}

const createPrescriptionItem = `-- name: CreatePrescriptionItem :one
INSERT INTO prescription_items (id, prescription_id, item_code, quantity, price)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, prescription_id, item_code, quantity, price
`

type CreatePrescriptionItemParams struct {
	ID             string
	PrescriptionID string
	ItemCode       string
	Quantity       int32
	Price          string
}

func (q *Queries) CreatePrescriptionItem(ctx context.Context, arg CreatePrescriptionItemParams) (PrescriptionItem, error) {
	row := q.db.QueryRowContext(ctx, createPrescriptionItem,
		arg.ID,
		arg.PrescriptionID,
		arg.ItemCode,
		arg.Quantity,
		arg.Price,
	)
	var i PrescriptionItem
	err := row.Scan(
		&i.ID,
		&i.PrescriptionID,
		&i.ItemCode,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const getEncounterPayment = `-- name: GetEncounterPayment :one
SELECT status
FROM encounter_payments
WHERE encounter_no = $1 LIMIT 1
`

func (q *Queries) GetEncounterPayment(ctx context.Context, encounterNo string) (string, error) {
	row := q.db.QueryRowContext(ctx, getEncounterPayment, encounterNo)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getInventoryItem = `-- name: GetInventoryItem :one
SELECT item_code, name, stock_quantity, price
FROM inventory
WHERE item_code = $1 LIMIT 1
`

func (q *Queries) GetInventoryItem(ctx context.Context, itemCode string) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventoryItem, itemCode)
	var i Inventory
	err := row.Scan(
		&i.ItemCode,
		&i.Name,
		&i.StockQuantity,
		&i.Price,
	)
	return i, err
}

const getInventoryItemForUpdate = `-- name: GetInventoryItemForUpdate :one
SELECT item_code, name, stock_quantity, price
FROM inventory
WHERE item_code = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetInventoryItemForUpdate(ctx context.Context, itemCode string) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventoryItemForUpdate, itemCode)
	var i Inventory
	err := row.Scan(
		&i.ItemCode,
		&i.Name,
		&i.StockQuantity,
		&i.Price,
	)
	return i, err
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, aggregate_type, event_type, payload, status, created_at
FROM outbox_events
WHERE status = 'PENDING'
ORDER BY created_at ASC LIMIT 100
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context) ([]OutboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, getPendingOutboxEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPharmacyWaitAggregate = `-- name: GetPharmacyWaitAggregate :one
SELECT average_wait_minutes, sample_count
FROM pharmacy_wait_time_aggregates
WHERE diagnosis = $1 AND doctor_id = $2 AND department_code = $3 AND gender = $4 AND age_bracket = $5 AND is_compounded = $6
`

type GetPharmacyWaitAggregateParams struct {
	Diagnosis      string
	DoctorID       string
	DepartmentCode string
	Gender         string
	AgeBracket     string
	IsCompounded   bool
}

type GetPharmacyWaitAggregateRow struct {
	AverageWaitMinutes int32
	SampleCount        int32
}

func (q *Queries) GetPharmacyWaitAggregate(ctx context.Context, arg GetPharmacyWaitAggregateParams) (GetPharmacyWaitAggregateRow, error) {
	row := q.db.QueryRowContext(ctx, getPharmacyWaitAggregate,
		arg.Diagnosis,
		arg.DoctorID,
		arg.DepartmentCode,
		arg.Gender,
		arg.AgeBracket,
		arg.IsCompounded,
	)
	var i GetPharmacyWaitAggregateRow
	err := row.Scan(&i.AverageWaitMinutes, &i.SampleCount)
	return i, err
}

const getPharmacyWaitAggregateWithoutDiagnosis = `-- name: GetPharmacyWaitAggregateWithoutDiagnosis :one
SELECT COALESCE(AVG(average_wait_minutes), 0)::float8 AS avg_wait_minutes
FROM pharmacy_wait_time_aggregates
WHERE doctor_id = $1 AND department_code = $2 AND gender = $3 AND age_bracket = $4 AND is_compounded = $5
`

type GetPharmacyWaitAggregateWithoutDiagnosisParams struct {
	DoctorID       string
	DepartmentCode string
	Gender         string
	AgeBracket     string
	IsCompounded   bool
}

func (q *Queries) GetPharmacyWaitAggregateWithoutDiagnosis(ctx context.Context, arg GetPharmacyWaitAggregateWithoutDiagnosisParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getPharmacyWaitAggregateWithoutDiagnosis,
		arg.DoctorID,
		arg.DepartmentCode,
		arg.Gender,
		arg.AgeBracket,
		arg.IsCompounded,
	)
	var avg_wait_minutes float64
	err := row.Scan(&avg_wait_minutes)
	return avg_wait_minutes, err
}

const getPrescription = `-- name: GetPrescription :one
SELECT id, encounter_no, status, created_at, updated_at, is_compounded, notes, diagnosis, gender, age_bracket, doctor_id, department_code
FROM prescriptions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPrescription(ctx context.Context, id string) (Prescription, error) {
	row := q.db.QueryRowContext(ctx, getPrescription, id)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.EncounterNo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsCompounded,
		&i.Notes,
		&i.Diagnosis,
		&i.Gender,
		&i.AgeBracket,
		&i.DoctorID,
		&i.DepartmentCode,
	)
	return i, err
}

const getPrescriptionItems = `-- name: GetPrescriptionItems :many
SELECT id, prescription_id, item_code, quantity, price
FROM prescription_items
WHERE prescription_id = $1
`

func (q *Queries) GetPrescriptionItems(ctx context.Context, prescriptionID string) ([]PrescriptionItem, error) {
	rows, err := q.db.QueryContext(ctx, getPrescriptionItems, prescriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrescriptionItem
	for rows.Next() {
		var i PrescriptionItem
		if err := rows.Scan(
			&i.ID,
			&i.PrescriptionID,
			&i.ItemCode,
			&i.Quantity,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOutboxEventStatus = `-- name: UpdateOutboxEventStatus :exec
UPDATE outbox_events
SET status = $2
WHERE id = $1
`

type UpdateOutboxEventStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateOutboxEventStatus(ctx context.Context, arg UpdateOutboxEventStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOutboxEventStatus, arg.ID, arg.Status)
	return err
}

const updatePrescriptionStatus = `-- name: UpdatePrescriptionStatus :one
UPDATE prescriptions
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, encounter_no, status, created_at, updated_at, is_compounded, notes, diagnosis, gender, age_bracket, doctor_id, department_code
`

type UpdatePrescriptionStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdatePrescriptionStatus(ctx context.Context, arg UpdatePrescriptionStatusParams) (Prescription, error) {
	row := q.db.QueryRowContext(ctx, updatePrescriptionStatus, arg.ID, arg.Status)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.EncounterNo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsCompounded,
		&i.Notes,
		&i.Diagnosis,
		&i.Gender,
		&i.AgeBracket,
		&i.DoctorID,
		&i.DepartmentCode,
	)
	return i, err
}

const updateStock = `-- name: UpdateStock :exec
UPDATE inventory
SET stock_quantity = stock_quantity - $2
WHERE item_code = $1
`

type UpdateStockParams struct {
	ItemCode      string
	StockQuantity int32
}

func (q *Queries) UpdateStock(ctx context.Context, arg UpdateStockParams) error {
	_, err := q.db.ExecContext(ctx, updateStock, arg.ItemCode, arg.StockQuantity)
	return err
}

const upsertEncounterPayment = `-- name: UpsertEncounterPayment :exec
INSERT INTO encounter_payments (encounter_no, status, paid_at, updated_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
ON CONFLICT (encounter_no)
DO UPDATE SET status = EXCLUDED.status, paid_at = EXCLUDED.paid_at, updated_at = CURRENT_TIMESTAMP
`

type UpsertEncounterPaymentParams struct {
	EncounterNo string
	Status      string
	PaidAt      sql.NullTime
}

func (q *Queries) UpsertEncounterPayment(ctx context.Context, arg UpsertEncounterPaymentParams) error {
	_, err := q.db.ExecContext(ctx, upsertEncounterPayment, arg.EncounterNo, arg.Status, arg.PaidAt)
	return err
}

const upsertPharmacyWaitAggregate = `-- name: UpsertPharmacyWaitAggregate :exec
INSERT INTO pharmacy_wait_time_aggregates (diagnosis, doctor_id, department_code, gender, age_bracket, is_compounded, average_wait_minutes, sample_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (diagnosis, doctor_id, department_code, gender, age_bracket, is_compounded) 
DO UPDATE SET 
    average_wait_minutes = EXCLUDED.average_wait_minutes,
    sample_count = EXCLUDED.sample_count,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertPharmacyWaitAggregateParams struct {
	Diagnosis          string
	DoctorID           string
	DepartmentCode     string
	Gender             string
	AgeBracket         string
	IsCompounded       bool
	AverageWaitMinutes int32
	SampleCount        int32
}

func (q *Queries) UpsertPharmacyWaitAggregate(ctx context.Context, arg UpsertPharmacyWaitAggregateParams) error {
	_, err := q.db.ExecContext(ctx, upsertPharmacyWaitAggregate,
		arg.Diagnosis,
		arg.DoctorID,
		arg.DepartmentCode,
		arg.Gender,
		arg.AgeBracket,
		arg.IsCompounded,
		arg.AverageWaitMinutes,
		arg.SampleCount,
	)
	return err
}
